### ISSUE TITLE
[feature request] rb>: want ruby error message and stacktrace in ${error}

### ISSUE THREAD

**Issue by sonots-zozo** [treasure-data/digdag#1013]
We currently use `${error.message}` and `${error.stacktrace}` to notify error messages to slack.

However, errors of rb>: operator are currently like:

Error Message

`Ruby command failed with code 1 (runtime)`

StackTrace

```
io.digdag.standards.operator.RbOperatorFactory$RbOperator.runCode(RbOperatorFactory.java:161),
io.digdag.standards.operator.RbOperatorFactory$RbOperator.runTask(RbOperatorFactory.java:92), 
io.digdag.util.BaseOperator.run(BaseOperator.java:35), 
io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:312), 
io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:254), 
io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137), 
io.digdag.core.agent.ExtractArchiveWorkspaceManager.withExtractedArchive(ExtractArchiveWorkspaceManager.java:77), 
io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135), 
io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119), 
io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127), 
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511), 
java.util.concurrent.FutureTask.run(FutureTask.java:266), 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), 
java.lang.Thread.run(Thread.java:748)
```

It has almost no information.
We want ruby error message and ruby stacktrace here.

**Comment by hiroyuki-sato** [comment]
This issue related to #938.
Another operator also has no information.

**Comment by sonots** [comment]
Let me take a note about current implmentation:

https://github.com/treasure-data/digdag/blob/75fb136f7a41d0b305469db4de50655ec2d5e152/digdag-spi/src/main/java/io/digdag/spi/TaskExecutionException.java#L41-L44 is the place to building `error` objects.

rb>: operator simply throws RuntimeException with a message `"Ruby command failed with code " + ecode` https://github.com/treasure-data/digdag/blob/75fb136f7a41d0b305469db4de50655ec2d5e152/digdag-standards/src/main/java/io/digdag/standards/operator/RbOperatorFactory.java#L161.

We see ruby level stacktrace from digdag logs as:
 
```
2019-02-25 00:20:42 +0900 [INFO] (0017@[0:default]+ruby_sample+ruby): rb>: RubySample.foo
/Users/naotoshi.seo/digdag-examples/ruby_sample.rb:5:in `foo': a (RuntimeError)
        from -:271:in `<main>'
2019-02-25 00:20:42 +0900 [ERROR] (0017@[0:default]+ruby_sample+ruby): Task failed with unexpected error: Ruby command failed with code 1
java.lang.RuntimeException: Ruby command failed with code 1
        at io.digdag.standards.operator.RbOperatorFactory$RbOperator.runCode(RbOperatorFactory.java:164)
        at io.digdag.standards.operator.RbOperatorFactory$RbOperator.runTask(RbOperatorFactory.java:93)
        at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
        at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:312)
        at io.digdag.cli.Run$OperatorManagerWithSkip.callExecutor(Run.java:705)
        at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:254)
        at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137)
        at io.digdag.core.agent.LocalWorkspaceManager.withExtractedArchive(LocalWorkspaceManager.java:25)
        at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135)
        at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119)
        at io.digdag.cli.Run$OperatorManagerWithSkip.run(Run.java:687)
        at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

The ruby level stacktrace is simply coming from STDERR. No data structure is available yet.

If our ruby task script is doing `STDERR.puts` (actually, or `STDOUT.puts`), these strings are also mixed with Ruby level stacktrace.

-----------

It looks difficult to extract only ruby level error message and ruby level error stacktrace. Hmm 🤔

**Comment by sonots** [comment]
begin; rescue at https://github.com/treasure-data/digdag/blob/75fb136f7a41d0b305469db4de50655ec2d5e152/digdag-standards/src/main/resources/digdag/standards/rb/runner.rb#L262-L285, and outputs into `out_file` would make it possible to get ruby error structure from it.
