### ISSUE TITLE
Operations within "for_each>:" operator executed twice when retried

### ISSUE THREAD

**Issue by to-lz1** [treasure-data/digdag#1131]
DIgdag version: 0.9.37

We have `_retry` parameter and `for_each` operator in our workflow.
When workflow failed, workflow itself successfully restarted.
But each operation in `_do` executed twice, even if the error came from outside of `for_each` operator.

this .dig file will reproduce the issue.

```
timezone: Asia/Tokyo

_retry: 2

+test:
  _export:
    counts: [
      0, 1, 2
    ]

  +echo:
    for_each>:
      count: ${counts}
    _do:
      echo>: ${count}  

  +failure:
    for_each>:
      count: ${counts}
    _do:
      sh>: exit ${count}
```

```
2019-06-04 14:41:25 +0900: Digdag v0.9.37
2019-06-04 14:41:36 +0900 [WARN] (main): Using a new session time 2019-06-04T00:00:00+09:00.
2019-06-04 14:41:36 +0900 [INFO] (main): Starting a new session project id=1 workflow name=z session_time=2019-06-04T00:00:00+09:00
2019-06-04 14:41:37 +0900 [INFO] (0016@[0:default]+z+test+echo): for_each>: {count=[0,1,2]}
2019-06-04 14:41:37 +0900 [INFO] (0016@[0:default]+z+test+echo^sub+for-0=count=0=0): echo>: 0
0
2019-06-04 14:41:37 +0900 [INFO] (0016@[0:default]+z+test+echo^sub+for-0=count=1=1): echo>: 1
1
2019-06-04 14:41:37 +0900 [INFO] (0016@[0:default]+z+test+echo^sub+for-0=count=2=2): echo>: 2
2
2019-06-04 14:41:37 +0900 [INFO] (0016@[0:default]+z+test+failure): for_each>: {count=[0,1,2]}
2019-06-04 14:41:38 +0900 [INFO] (0016@[0:default]+z+test+failure^sub+for-0=count=0=0): sh>: exit 0
2019-06-04 14:41:38 +0900 [INFO] (0016@[0:default]+z+test+failure^sub+for-0=count=1=1): sh>: exit 1
2019-06-04 14:41:38 +0900 [ERROR] (0016@[0:default]+z+test+failure^sub+for-0=count=1=1): Task failed with unexpected error: Command failed with code 1
java.lang.RuntimeException: Command failed with code 1
        at io.digdag.standards.operator.ShOperatorFactory$ShOperator.runTask(ShOperatorFactory.java:143)
        at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
        at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:315)
        at io.digdag.cli.Run$OperatorManagerWithSkip.callExecutor(Run.java:705)
        at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:257)
        at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137)
        at io.digdag.core.agent.LocalWorkspaceManager.withExtractedArchive(LocalWorkspaceManager.java:25)
        at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135)
        at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119)
        at io.digdag.cli.Run$OperatorManagerWithSkip.run(Run.java:687)
        at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-06-04 14:41:38 +0900 [INFO] (0016@[0:default]+z+test+echo): for_each>: {count=[0,1,2]}
2019-06-04 14:41:38 +0900 [INFO] (0016@[0:default]+z+test+echo^sub+for-0=count=0=0): echo>: 0
0
2019-06-04 14:41:38 +0900 [INFO] (0018@[0:default]+z+test+echo^sub+for-0=count=0=0): echo>: 0
0
2019-06-04 14:41:39 +0900 [INFO] (0018@[0:default]+z+test+echo^sub+for-0=count=1=1): echo>: 1
1
2019-06-04 14:41:39 +0900 [INFO] (0016@[0:default]+z+test+echo^sub+for-0=count=1=1): echo>: 1
1
2019-06-04 14:41:39 +0900 [INFO] (0016@[0:default]+z+test+echo^sub+for-0=count=2=2): echo>: 2
2
2019-06-04 14:41:39 +0900 [INFO] (0018@[0:default]+z+test+echo^sub+for-0=count=2=2): echo>: 2
2
2019-06-04 14:41:39 +0900 [INFO] (0018@[0:default]+z+test+failure): for_each>: {count=[0,1,2]}
2019-06-04 14:41:39 +0900 [INFO] (0016@[0:default]+z+test+failure^sub+for-0=count=0=0): sh>: exit 0
2019-06-04 14:41:39 +0900 [INFO] (0018@[0:default]+z+test+failure^sub+for-0=count=0=0): sh>: exit 0
2019-06-04 14:41:39 +0900 [INFO] (0018@[0:default]+z+test+failure^sub+for-0=count=1=1): sh>: exit 1
2019-06-04 14:41:39 +0900 [INFO] (0016@[0:default]+z+test+failure^sub+for-0=count=1=1): sh>: exit 1
2019-06-04 14:41:39 +0900 [ERROR] (0016@[0:default]+z+test+failure^sub+for-0=count=1=1): Task failed with unexpected error: Command failed with code 1
java.lang.RuntimeException: Command failed with code 1
        at io.digdag.standards.operator.ShOperatorFactory$ShOperator.runTask(ShOperatorFactory.java:143)
        at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
        at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:315)
        at io.digdag.cli.Run$OperatorManagerWithSkip.callExecutor(Run.java:705)
        at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:257)
        at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137)
        at io.digdag.core.agent.LocalWorkspaceManager.withExtractedArchive(LocalWorkspaceManager.java:25)
        at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135)
        at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119)
        at io.digdag.cli.Run$OperatorManagerWithSkip.run(Run.java:687)
        at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

We observed this: 
- on client mode of version 0.9.35
- on client mode of version 0.9.37(used `digdag selfupdate`)
- on server mode of version 0.9.35

On the other hand, version 0.9.31 doesn't reproduce the issue; Each operation executed exactly once, when task retried (and this is what we expected, isn't it?).

**Comment by yoyama** [comment]
Thanks for the report. I also confirmed your procedure.
I need more time to investigate it.
