### ISSUE TITLE
Scheduler fails to configure authenticatorClass in local mode

### ISSUE THREAD

**Issue by amatissart** [treasure-data/digdag#1243]
Tested with digdag **v0.9.39**

I am trying to run the scheduler in local mode with `digdag scheduler`, and a simple .dig file in the current directory. The scheduler fails with several errors such as:
<details><summary><b>Show error</b></summary>
<p>

```
2019-10-18 22:22:12 +0200 [ERROR] (XNIO-1 task-1): UT005023: Exception handling request to /api/workflows
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalArgumentException: Configured authenticatorClass not found: io.digdag.standards.auth.jwt.JwtAuthenticator
  at io.digdag.server.ServerModule$AuthenticatorProvider.<init>(ServerModule.java:176)
  while locating io.digdag.server.ServerModule$AuthenticatorProvider
  while locating io.digdag.spi.Authenticator
    for parameter 0 at io.digdag.server.AuthRequestFilter.<init>(AuthRequestFilter.java:28)
  while locating io.digdag.server.AuthRequestFilter
  while locating io.digdag.server.AuthRequestFilter annotated with @com.google.inject.internal.UniqueAnnotations$Internal(value=3)

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1047)
	at org.embulk.guice.InjectorProxy.getInstance(InjectorProxy.java:107)
	at io.digdag.guice.rs.GuiceRsApplicationServlet.init(GuiceRsApplicationServlet.java:45)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
	at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:250)
	at io.undertow.servlet.core.ManagedServlet.getServlet(ManagedServlet.java:171)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:84)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.digdag.guice.rs.server.undertow.UndertowServer$SetListenAddressNameServletFilter.doFilter(UndertowServer.java:139)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Configured authenticatorClass not found: io.digdag.standards.auth.jwt.JwtAuthenticator
	at io.digdag.server.ServerModule$AuthenticatorProvider.<init>(ServerModule.java:186)
	at io.digdag.server.ServerModule$AuthenticatorProvider$$FastClassByGuice$$6e5ddcdc.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	... 38 common frames omitted
```
</p>
</details>

---

As far as I understand, this may be due to how #1098 implemented `systemPlugins` loading. 

Bootstrapping the server via `digdag scheduler` seems to use an empty `PluginSet`: 

https://github.com/treasure-data/digdag/blob/aaefa00879e2a53bce21bd5df440fa6d0a02a461/digdag-server/src/main/java/io/digdag/server/ServerBootstrap.java#L43-L46

**Comment by hiroyuki-sato** [comment]
Hello, @amatissart 

Thank you for your report.
Could you tell me to reproduce steps?

It seems that `digdag scheduler` works fine in my environment.

I recommend you to use `digdag server` instead of `digdag scheduler`.
`digdag server` supports scheduled workflow and UI.

`digdag scheduler` just run schedule task on local workflow.
There is no UI.

## digdag scheduler test.

* OS: macOS 10.14.6
* java: 1.8.0_192-b12
* Digdag: v0.9.39

```yaml
timezone: UTC

schedule:
  minutes_interval>: 1

+task:
  echo>: "session: ${session_time}"
```

```
digdag scheduler
2019-10-21 19:00:32 +0900: Digdag v0.9.39
...
2019-10-21 19:01:02 +0900 [INFO] (0027@[0:default]+hoge+task): echo>: session: 2019-10-21T10:01:00+00:00
session: 2019-10-21T10:01:00+00:00
2019-10-21 19:02:00 +0900 [INFO] (scheduler-0): Starting a new session project id=1 workflow name=hoge session_time=2019-10-21T10:02:00+00:00
2019-10-21 19:02:00 +0900 [INFO] (scheduler-0): Updating next schedule time: sched=StoredSchedule{id=1, projectId=1, createdAt=2019-10-21T10:00:34Z, updatedAt=2019-10-21T10:01:01.012Z, lastSessionTime=2019-10-21T10:01:00Z, workflowName=hoge, workflowDefinitionId=1, nextRunTime=2019-10-21T10:02:00Z, nextScheduleTime=2019-10-21T10:02:00Z}, next=ScheduleTime{runTime=2019-10-21T10:03:00Z, time=2019-10-21T10:03:00Z}, lastSessionTime=2019-10-21T10:02:00Z
2019-10-21 19:02:00 +0900 [INFO] (0027@[0:default]+hoge+task): echo>: session: 2019-10-21T10:02:00+00:00
session: 2019-10-21T10:02:00+00:00
...
```

**Comment by amatissart** [comment]
* OS: Linux Mint 19.2
* java: openjdk 11.0.4 2019-07-16
* Digdag: v0.9.39

With the same .dif file
```yaml
timezone: UTC

schedule:
  minutes_interval>: 1

+task:
  echo>: "session: ${session_time}"
```

The error is indeed triggered when I am accessing the web UI after `digdag scheduler ` is launched.
("Workflows" and "Projects" pages remain empty).

```
2019-10-21 14:06:33 +0200: Digdag v0.9.39
...
2019-10-21 14:06:34 +0200 [INFO] (main): XNIO version 3.3.6.Final
2019-10-21 14:06:34 +0200 [INFO] (main): XNIO NIO Implementation Version 3.3.6.Final
2019-10-21 14:06:34 +0200 [INFO] (main): Starting server on 127.0.0.1:65432
2019-10-21 14:06:34 +0200 [INFO] (main): Bound on 127.0.0.1:65432 (api)
2019-10-21 14:06:40 +0200 [ERROR] (XNIO-1 task-8): UT005023: Exception handling request to /api/version
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalArgumentException: Configured authenticatorClass not found: io.digdag.standards.auth.jwt.JwtAuthenticator
  at io.digdag.server.ServerModule$AuthenticatorProvider.<init>(ServerModule.java:176)
  while locating io.digdag.server.ServerModule$AuthenticatorProvider
  while locating io.digdag.spi.Authenticator
    for parameter 0 at io.digdag.server.AuthRequestFilter.<init>(AuthRequestFilter.java:28)
  while locating io.digdag.server.AuthRequestFilter
  while locating io.digdag.server.AuthRequestFilter annotated with @com.google.inject.internal.UniqueAnnotations$Internal(value=3)
...
```

---

> digdag scheduler just run schedule task on local workflow. There is no UI.

That's maybe where I am mistaken. `digdag scheduler --help` describes options to bind an address and a port for web interface and api. Is it obsolete ? 
Yet, it seems to works as expected with v0.9.38.

**Comment by hiroyuki-sato** [comment]
Hello, @amatissart 

I recommend you to use `digdag server` instead of `scheduler.`
`scheduler` doesn't active maintain much as opposed to `server` and `local`

As far as I remember, digag ui down't work with `scheduler` mode.

**Comment by yoyama** [comment]
There is no activity. Close.
