### ISSUE TITLE
Error injecting constructor, java.lang.IllegalArgumentException when I deploy digdag docker.

### ISSUE THREAD

**Issue by sabi2345** [treasure-data/digdag#1285]
I deployed digdag docker on k8s in azure.
However, the docker was in an `Error injecting constructor, java.lang.IllegalArgumentException` .
It may be similar to [this issue](https://github.com/treasure-data/digdag/issues/551). 
I'd appreciate it, if you would check the cause.

- Dockerfile

```
FROM azul/zulu-openjdk:8

ENV DIGDAG_VERSION=0.9.40

# install embulk
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y install locales && \
    apt-get -y install curl && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8

# timezone (Asia/Tokyo)
ENV TZ JST-9

# install digdag
RUN curl -o /usr/local/bin/digdag --create-dirs -L "https://dl.digdag.io/digdag-${DIGDAG_VERSION}" && \
    chmod +x /usr/local/bin/digdag && \
    apt-get clean && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/* && \
    adduser --shell /sbin/nologin --disabled-password --gecos "" digdag

# install python3.7.5
RUN apt-get update && apt-get install -y \
    python3.7 \
    python3-pip

RUN pip3 install --upgrade \
    pip \
    setuptools

# Install Python modules needed by the Python app
ENV APP_PATH /opt/requirements
COPY requirements.txt $APP_PATH/
RUN pip install --no-cache-dir -r $APP_PATH/requirements.txt

USER digdag

WORKDIR /home/digdag

ENV PATH=${PATH}:/usr/local/bin

COPY digdag.properties $APP_PATH/

EXPOSE 65432

CMD ["sh","-c", "java -jar /usr/local/bin/digdag server -c /opt/requirements/digdag.properties --task-log /var/tmp --max-task-threads 4"]
```
I used PostgreSQL 9.6 or 11 and made digdag database.
After deploying, the following tables were made automatically, so the docker may be able to access the database.
```
queues
revisions
sessions
secrets
workflow_configs
session_monitors
queued_task_locks
task_dependencies
delayed_session_attempts
queue_settings
session_attempts
revision_archives
resuming_tasks
task_state_details
tasks
workflow_definitions
schedules
queued_tasks
task_details
projects
schema_migrations
task_archives
```

Error Message
```
2019-12-20 23:28:54 +0900: Digdag v0.9.40
error: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.IllegalArgumentException
  at io.digdag.core.crypto.SecretCryptoProvider.<init>(SecretCryptoProvider.java:21)
  while locating io.digdag.core.crypto.SecretCryptoProvider
  at io.digdag.server.ServerModule.bindSecrets(ServerModule.java:89)
  while locating io.digdag.core.crypto.SecretCrypto
Caused by: java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:128)
        at io.digdag.core.database.AESGCMSecretCrypto.<init>(AESGCMSecretCrypto.java:75)
        at io.digdag.core.crypto.SecretCryptoProvider.<init>(SecretCryptoProvider.java:24)
        at io.digdag.core.crypto.SecretCryptoProvider$$FastClassByGuice$$e1b8329e.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:60)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at org.embulk.guice.Bootstrap.start(Bootstrap.java:168)
        at org.embulk.guice.Bootstrap.build(Bootstrap.java:130)
        at org.embulk.guice.Bootstrap.initializeCloseable(Bootstrap.java:125)
        at io.digdag.guice.rs.server.undertow.UndertowBootstrap.initialize(UndertowBootstrap.java:70)
        at io.digdag.guice.rs.GuiceRsServletContainerInitializer.processBootstrap(GuiceRsServletContainerInitializer.java:61)
        at io.digdag.guice.rs.GuiceRsServletContainerInitializer.onStartup(GuiceRsServletContainerInitializer.java:36)
        at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:186)
        at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:171)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:234)
        at io.digdag.guice.rs.server.undertow.UndertowServer.start(UndertowServer.java:179)
        at io.digdag.server.ServerBootstrap.start(ServerBootstrap.java:81)
        at io.digdag.cli.Server.startServer(Server.java:135)
        at io.digdag.cli.Server.main(Server.java:100)
        at io.digdag.cli.Main.cli(Main.java:191)
        at io.digdag.cli.Main.main(Main.java:83)

2) Error injecting constructor, java.lang.IllegalArgumentException
  at io.digdag.core.crypto.SecretCryptoProvider.<init>(SecretCryptoProvider.java:21)
  while locating io.digdag.core.crypto.SecretCryptoProvider
  at io.digdag.server.ServerModule.bindSecrets(ServerModule.java:89)
  while locating io.digdag.core.crypto.SecretCrypto
    for the 4th parameter of io.digdag.core.database.DatabaseSecretStoreManager.<init>(DatabaseSecretStoreManager.java:19)
  while locating io.digdag.core.database.DatabaseSecretStoreManager
  at io.digdag.server.ServerModule.bindSecrets(ServerModule.java:90)
  while locating io.digdag.spi.SecretStoreManager
Caused by: java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:128)
        at io.digdag.core.database.AESGCMSecretCrypto.<init>(AESGCMSecretCrypto.java:75)
        at io.digdag.core.crypto.SecretCryptoProvider.<init>(SecretCryptoProvider.java:24)
        at io.digdag.core.crypto.SecretCryptoProvider$$FastClassByGuice$$e1b8329e.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:60)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at org.embulk.guice.Bootstrap.start(Bootstrap.java:168)
        at org.embulk.guice.Bootstrap.build(Bootstrap.java:130)
        at org.embulk.guice.Bootstrap.initializeCloseable(Bootstrap.java:125)
        at io.digdag.guice.rs.server.undertow.UndertowBootstrap.initialize(UndertowBootstrap.java:70)
        at io.digdag.guice.rs.GuiceRsServletContainerInitializer.processBootstrap(GuiceRsServletContainerInitializer.java:61)
        at io.digdag.guice.rs.GuiceRsServletContainerInitializer.onStartup(GuiceRsServletContainerInitializer.java:36)
        at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:186)
        at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:171)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:234)
        at io.digdag.guice.rs.server.undertow.UndertowServer.start(UndertowServer.java:179)
        at io.digdag.server.ServerBootstrap.start(ServerBootstrap.java:81)
        at io.digdag.cli.Server.startServer(Server.java:135)
        at io.digdag.cli.Server.main(Server.java:100)
        at io.digdag.cli.Main.cli(Main.java:191)
        at io.digdag.cli.Main.main(Main.java:83)

3) Error injecting constructor, java.lang.IllegalArgumentException
  at io.digdag.core.crypto.SecretCryptoProvider.<init>(SecretCryptoProvider.java:21)
  while locating io.digdag.core.crypto.SecretCryptoProvider
  at io.digdag.server.ServerModule.bindSecrets(ServerModule.java:89)
  while locating io.digdag.core.crypto.SecretCrypto
    for the 4th parameter of io.digdag.core.database.DatabaseSecretStoreManager.<init>(DatabaseSecretStoreManager.java:19)
  while locating io.digdag.core.database.DatabaseSecretStoreManager
  at io.digdag.server.ServerModule.bindSecrets(ServerModule.java:90)
  while locating io.digdag.spi.SecretStoreManager
    for the 8th parameter of io.digdag.core.agent.OperatorManager.<init>(OperatorManager.java:74)
  at io.digdag.core.agent.LocalAgentModule.configure(LocalAgentModule.java:23) (via modules: com.google.inject.util.Modules$OverrideModule -> io.digdag.core.agent.LocalAgentModule)
  while locating io.digdag.core.agent.OperatorManager
Caused by: java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:128)
        at io.digdag.core.database.AESGCMSecretCrypto.<init>(AESGCMSecretCrypto.java:75)
        at io.digdag.core.crypto.SecretCryptoProvider.<init>(SecretCryptoProvider.java:24)
        at io.digdag.core.crypto.SecretCryptoProvider$$FastClassByGuice$$e1b8329e.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:60)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at org.embulk.guice.Bootstrap.start(Bootstrap.java:168)
        at org.embulk.guice.Bootstrap.build(Bootstrap.java:130)
        at org.embulk.guice.Bootstrap.initializeCloseable(Bootstrap.java:125)
        at io.digdag.guice.rs.server.undertow.UndertowBootstrap.initialize(UndertowBootstrap.java:70)
        at io.digdag.guice.rs.GuiceRsServletContainerInitializer.processBootstrap(GuiceRsServletContainerInitializer.java:61)
        at io.digdag.guice.rs.GuiceRsServletContainerInitializer.onStartup(GuiceRsServletContainerInitializer.java:36)
        at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:186)
        at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:171)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:234)
        at io.digdag.guice.rs.server.undertow.UndertowServer.start(UndertowServer.java:179)
        at io.digdag.server.ServerBootstrap.start(ServerBootstrap.java:81)
        at io.digdag.cli.Server.startServer(Server.java:135)
        at io.digdag.cli.Server.main(Server.java:100)
        at io.digdag.cli.Main.cli(Main.java:191)
        at io.digdag.cli.Main.main(Main.java:83)

4) Error injecting constructor, java.lang.IllegalArgumentException
  at io.digdag.core.crypto.SecretCryptoProvider.<init>(SecretCryptoProvider.java:21)
  while locating io.digdag.core.crypto.SecretCryptoProvider
  at io.digdag.server.ServerModule.bindSecrets(ServerModule.java:89)
  while locating io.digdag.core.crypto.SecretCrypto
    for the 4th parameter of io.digdag.core.database.DatabaseSecretStoreManager.<init>(DatabaseSecretStoreManager.java:19)
  while locating io.digdag.core.database.DatabaseSecretStoreManager
  at io.digdag.server.ServerModule.bindSecrets(ServerModule.java:90)
  while locating io.digdag.spi.SecretStoreManager
    for the 8th parameter of io.digdag.core.agent.OperatorManager.<init>(OperatorManager.java:74)
  at io.digdag.core.agent.LocalAgentModule.configure(LocalAgentModule.java:23) (via modules: com.google.inject.util.Modules$OverrideModule -> io.digdag.core.agent.LocalAgentModule)
  while locating io.digdag.core.agent.OperatorManager
    for the 4th parameter of io.digdag.core.agent.LocalAgentManager.<init>(LocalAgentManager.java:33)
  at io.digdag.core.agent.LocalAgentModule.configure(LocalAgentModule.java:30) (via modules: com.google.inject.util.Modules$OverrideModule -> io.digdag.core.agent.LocalAgentModule)
  while locating io.digdag.core.agent.LocalAgentManager
Caused by: java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:128)
        at io.digdag.core.database.AESGCMSecretCrypto.<init>(AESGCMSecretCrypto.java:75)
        at io.digdag.core.crypto.SecretCryptoProvider.<init>(SecretCryptoProvider.java:24)
        at io.digdag.core.crypto.SecretCryptoProvider$$FastClassByGuice$$e1b8329e.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:60)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at org.embulk.guice.Bootstrap.start(Bootstrap.java:168)
        at org.embulk.guice.Bootstrap.build(Bootstrap.java:130)
        at org.embulk.guice.Bootstrap.initializeCloseable(Bootstrap.java:125)
        at io.digdag.guice.rs.server.undertow.UndertowBootstrap.initialize(UndertowBootstrap.java:70)
        at io.digdag.guice.rs.GuiceRsServletContainerInitializer.processBootstrap(GuiceRsServletContainerInitializer.java:61)
        at io.digdag.guice.rs.GuiceRsServletContainerInitializer.onStartup(GuiceRsServletContainerInitializer.java:36)
        at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:186)
        at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:171)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:234)
        at io.digdag.guice.rs.server.undertow.UndertowServer.start(UndertowServer.java:179)
        at io.digdag.server.ServerBootstrap.start(ServerBootstrap.java:81)
        at io.digdag.cli.Server.startServer(Server.java:135)
        at io.digdag.cli.Server.main(Server.java:100)
        at io.digdag.cli.Main.cli(Main.java:191)
        at io.digdag.cli.Main.main(Main.java:83)

4 errors (runtime)
```

**Comment by hiroyuki-sato** [comment]
Hello, @sabi2345 

I suspect that you use an incorrect secret key.
Does your secret use 128bit(16byte) length?

> It must be a valid 128-bit AES key, base64 encoded.

http://docs.digdag.io/command_reference.html#secret-encryption-key

Good

```
echo -n '16_bytes_phrase!' | openssl base64
MTZfYnl0ZXNfcGhyYXNlIQ==
```

digdag.conf


```
echo -n 'hoge' | openssl base64
aG9nZQ==
```

BAD( too short key).

```
# short
digdag.secret-encryption-key = aG9nZQ==
```

I got the same error when I use the incorrect secret.

```
digdag server -m -c digdag.conf
2019-12-23 17:15:18 +0900: Digdag v0.9.40
error: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.IllegalArgumentException
  at io.digdag.core.crypto.SecretCryptoProvider.<init>(SecretCryptoProvider.java:21)
  while locating io.digdag.core.crypto.SecretCryptoProvider
  at io.digdag.server.ServerModule.bindSecrets(ServerModule.java:89)
  while locating io.digdag.core.crypto.SecretCrypto
Caused by: java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:128)
	at io.digdag.core.database.AESGCMSecretCrypto.<init>(AESGCMSecretCrypto.java:75)
	at io.digdag.core.crypto.SecretCryptoProvider.<init>(SecretCryptoProvider.java:24)
	at io.digdag.core.crypto.SecretCryptoProvider$$FastClassByGuice$$e1b8329e.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java
```

**Comment by sabi2345** [comment]
Hello, @hiroyuki-sato 
This problem was resolved thanks to your support.
I set the short secret key, so I change it to a 16bit phrase and digdag can be runining.
