### ISSUE TITLE
Could not unmarshal stored params to Config class with KubernetesComamndExecutor.

### ISSUE THREAD

**Issue by TrsNium** [treasure-data/digdag#1339]
When trying to store param with rb operator in v0.10 kubernetes command executor, the following error occurs.

```
2020-01-27 05:00:29 +0000 [DEBUG] (0075@[0:hairstyle-dev]+scoring+load_config) io.digdag.server.metrics.DigdagTimedMethodInterceptor: invocationMain Failed. io.digdag.spi.TaskExecutionException: io.digdag.spi.TaskExecutionException: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No 'injectableValues' configured, cannot inject value with id [com.fasterxml.jackson.databind.ObjectMapper]
 at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 888]
2020-01-27 05:00:29 +0000 [DEBUG] (0075@[0:hairstyle-dev]+scoring+load_config) io.digdag.server.metrics.DigdagTimedMethodInterceptor: invocationMain Failed. io.digdag.spi.TaskExecutionException: io.digdag.spi.TaskExecutionException: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No 'injectableValues' configured, cannot inject value with id [com.fasterxml.jackson.databind.ObjectMapper]
 at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 888]
2020-01-27 05:00:29 +0000 [ERROR] (0075@[0:hairstyle-dev]+scoring+load_config) io.digdag.core.agent.OperatorManager: Task failed, retrying
io.digdag.spi.TaskExecutionException: io.digdag.spi.TaskExecutionException: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No 'injectableValues' configured, cannot inject value with id [com.fasterxml.jackson.databind.ObjectMapper]
 at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 888]
	at io.digdag.spi.TaskExecutionException.ofNextPollingWithCause(TaskExecutionException.java:85)
	at io.digdag.util.BaseOperator.run(BaseOperator.java:54)
	at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:330)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invokeMain(DigdagTimedMethodInterceptor.java:58)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invoke(DigdagTimedMethodInterceptor.java:31)
	at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:271)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invokeMain(DigdagTimedMethodInterceptor.java:58)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invoke(DigdagTimedMethodInterceptor.java:31)
	at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:144)
	at io.digdag.core.agent.ExtractArchiveWorkspaceManager.withExtractedArchive(ExtractArchiveWorkspaceManager.java:77)
	at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:142)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invokeMain(DigdagTimedMethodInterceptor.java:58)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invoke(DigdagTimedMethodInterceptor.java:31)
	at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:125)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invokeMain(DigdagTimedMethodInterceptor.java:58)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invoke(DigdagTimedMethodInterceptor.java:31)
	at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.digdag.spi.TaskExecutionException: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No 'injectableValues' configured, cannot inject value with id [com.fasterxml.jackson.databind.ObjectMapper]
 at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 888]
	at io.digdag.spi.TaskExecutionException.ofNextPollingWithCause(TaskExecutionException.java:85)
	at io.digdag.util.BaseOperator.run(BaseOperator.java:54)
	at io.digdag.plugin.gke.GkeOperatorFactory$GkeOperator.runTask(GkeOperatorFactory.java:113)
	at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
	... 20 common frames omitted
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No 'injectableValues' configured, cannot inject value with id [com.fasterxml.jackson.databind.ObjectMapper]
 at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 888]
	at com.google.common.base.Throwables.propagate(Throwables.java:241)
	at io.digdag.standards.operator.RbOperatorFactory$RbOperator.runTask(RbOperatorFactory.java:104)
	at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
	... 22 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No 'injectableValues' configured, cannot inject value with id [com.fasterxml.jackson.databind.ObjectMapper]
 at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 888]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1452)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:313)
	at com.fasterxml.jackson.databind.DeserializationContext.findInjectableValue(DeserializationContext.java:379)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator._createUsingDelegate(StdValueInstantiator.java:534)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDelegate(StdValueInstantiator.java:298)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1283)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4014)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3071)
	at io.digdag.standards.operator.RbOperatorFactory$RbOperator.runCode(RbOperatorFactory.java:174)
	at io.digdag.standards.operator.RbOperatorFactory$RbOperator.runTask(RbOperatorFactory.java:101)
	... 23 common frames omitted
2020-01-27 05:00:29 +0000 [DEBUG] (workflow-executor-0) io.digdag.core.workflow.WorkflowExecutor: Queuing task of attempt_id=22: id=296 +scoring+load_config
```

This is where the error occurred.
https://github.com/treasure-data/digdag/blob/cd45f32a02a874ae5139fa8c78c4724f0a2ce180/digdag-standards/src/main/java/io/digdag/standards/operator/RbOperatorFactory.java#L171

The json you are reading is as follows.
```json
"{"subtask_config":{},"export_params":{},"store_params":{"IMAGE_DIR":"/mnt/sync-images"}}";
```

**Comment by TrsNium** [comment]
No error occurred when using the same ObjectMapper as below line.
https://github.com/treasure-data/digdag/blob/cfc6cc23b52cc3e1d27f639662f6266ad97d7c38/digdag-client/src/main/java/io/digdag/client/DigdagClient.java#L181-L194

The problem was that the above settings were not set in the ObjectMapper injected into the custom digdag plugin.
