### ISSUE TITLE
Question: omit java stack trace

### ISSUE THREAD

**Issue by ehaupt** [treasure-data/digdag#1371]
Is there a way to omit the java stack trace if a task fails?

For instance:

usecase.dig
```
timezone: UTC

+taskwillfail:
  sh>: ./usecase.sh
```
usecase.sh
```
#!/bin/sh
echo "I will always fail."
exit 2
```
Output:
```
2020-03-03 12:29:30 +0100: Digdag v0.9.41
2020-03-03 12:29:32 +0100 [WARN] (main): Using a new session time 2020-03-03T00:00:00+00:00.
2020-03-03 12:29:32 +0100 [INFO] (main): Using session /tmp/usecase/.digdag/status/20200303T000000+0000.
2020-03-03 12:29:32 +0100 [INFO] (main): Starting a new session project id=1 workflow name=usecase session_time=2020-03-03T00:00:00+00:00
2020-03-03 12:29:34 +0100 [INFO] (0018@[0:default]+usecase+taskwillfail): sh>: ./usecase.sh
I will always fail.
2020-03-03 12:29:34 +0100 [ERROR] (0018@[0:default]+usecase+taskwillfail): Task failed with unexpected error: Command failed with code 2
java.lang.RuntimeException: Command failed with code 2
        at io.digdag.standards.operator.ShOperatorFactory$ShOperator.runTask(ShOperatorFactory.java:143)
        at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
        at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:315)
        at io.digdag.cli.Run$OperatorManagerWithSkip.callExecutor(Run.java:705)
        at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:257)
        at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137)
        at io.digdag.core.agent.LocalWorkspaceManager.withExtractedArchive(LocalWorkspaceManager.java:25)
        at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135)
        at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119)
        at io.digdag.cli.Run$OperatorManagerWithSkip.run(Run.java:687)
        at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-03-03 12:29:35 +0100 [INFO] (0018@[0:default]+usecase^failure-alert): type: notify
error: 
  * +usecase+taskwillfail:
    Command failed with code 2 (runtime)

Task state is saved at /tmp/usecase/.digdag/status/20200303T000000+0000 directory.
  * Use --session <daily | hourly | "yyyy-MM-dd[ HH:mm:ss]"> to not reuse the last session time.
  * Use --rerun, --start +NAME, or --goal +NAME argument to rerun skipped tasks.
```

Output I am trying to achieve:
```
2020-03-03 12:29:30 +0100: Digdag v0.9.41
2020-03-03 12:29:32 +0100 [WARN] (main): Using a new session time 2020-03-03T00:00:00+00:00.
2020-03-03 12:29:32 +0100 [INFO] (main): Using session /tmp/usecase/.digdag/status/20200303T000000+0000.
2020-03-03 12:29:32 +0100 [INFO] (main): Starting a new session project id=1 workflow name=usecase session_time=2020-03-03T00:00:00+00:00
2020-03-03 12:29:34 +0100 [INFO] (0018@[0:default]+usecase+taskwillfail): sh>: ./usecase.sh
I will always fail.
2020-03-03 12:29:34 +0100 [ERROR] (0018@[0:default]+usecase+taskwillfail): Task failed with unexpected error: Command failed with code 2
2020-03-03 12:29:35 +0100 [INFO] (0018@[0:default]+usecase^failure-alert): type: notify
error: 
  * +usecase+taskwillfail:
    Command failed with code 2 (runtime)

Task state is saved at /tmp/usecase/.digdag/status/20200303T000000+0000 directory.
  * Use --session <daily | hourly | "yyyy-MM-dd[ HH:mm:ss]"> to not reuse the last session time.
  * Use --rerun, --start +NAME, or --goal +NAME argument to rerun skipped tasks.
```

**Comment by hiroyuki-sato** [comment]
Hello, @ehaupt 

As far as I know, there is no option.
Why do you want to disable it? Is it `sh>` operator only?

**Comment by ehaupt** [comment]
Hello, @hiroyuki-sato 

I would prefer to be able to disable it for all operators.
In our setup we archive the attempts in central log facility. The exit code is definitely useful but the whole stack trace does not have any benefit but makes it hard to find the relevant error message.
Maybe something like

```yml
_export:
  verbose: false
```
or
```yml
_export:
  debuglevel: 0 # 0 quiet (exit code only), 1 more verbose, 2 full stack trace
```
could be introduced?

**Comment by hiroyuki-sato** [comment]
Hello, @ehaupt 

Thank you for your comment.
I'm not sure how to implement `verbose` option. 

This is my (a Digdag user) opinion.
Generally, digdag expect exit status 0 in `sh>` operator.
Other status treats as an error. In that case, a stack trace is an important information for many cases.

Additionally, another non-script operator, for Example `pg>` and `bq>` doesn't return status code.
In that case, a stack trace is the only useful information for knowing the error.

That's why, I think disable stack trace option doesn't useful for digdag users.

**Comment by ehaupt** [comment]
Hello, @hiroyuki-sato 

Should digdag tasks by design always exit with status 0 regardless of the result? I was using the exit code to signal digdag whether a task was successful or not.

Just out of curiosity, how do you signal digdag the result of a task? By setting certain values in the env store?

**Comment by hiroyuki-sato** [comment]
Hello, @ehaupt 

I mean, script operators (`sh>`,`rb>` and `py>`) 
* exit status 0: success
* other code: fail (raise an exception and show stack trace)

For example, If `something.sh` exit status 0, digdag process +task2. otherwise, digdag doesn't process +task2. (process `_error` section)
Please see [Dynamic task generation and _check/_error tasks](http://docs.digdag.io/concepts.html#dynamic-task-generation-and-check-error-tasks)

```yaml
+task1
  sh>: something.sh

+task2:
  echo>: done
```

Could you tell me more detail about a signal part?

https://github.com/treasure-data/digdag/blob/6f753b9b11bdddc3c214c66c1da201ae283bc2af/digdag-standards/src/main/java/io/digdag/standards/operator/RbOperatorFactory.java#L182

https://github.com/treasure-data/digdag/blob/6f753b9b11bdddc3c214c66c1da201ae283bc2af/digdag-standards/src/main/java/io/digdag/standards/operator/ShOperatorFactory.java#L142

https://github.com/treasure-data/digdag/blob/6f753b9b11bdddc3c214c66c1da201ae283bc2af/digdag-standards/src/main/java/io/digdag/standards/operator/PyOperatorFactory.java#L176

**Comment by hiroyuki-sato** [comment]
Hello, @ehaupt 

This is the other example.

```yaml
timezone: UTC

+task1:
  sh>: ./test.sh
  _error:
    +error_task:
      # This is just an example.
      # you can use slack>, mail> or something.
      echo>: "+task1 failed"

+task2:
  echo>: "task completed"
```

```bash
#!/bin/bash

trap "echo $0 execution failed ; exit 2" 15

sleep 2
kill $$

exit 0
```

If you want to use shell results in Digadg [digdag-plugin-shresult](https://github.com/takemikami/digdag-plugin-shresult) may help.
[Author's blog Google translate](https://translate.google.com/translate?sl=ja&tl=en&u=http%3A%2F%2Ftakemikami.com%2F2018%2F06%2F08%2FforeachDigdag.html)

I'm maintaining [Digdag Workflow engine link collection](https://dev.to/hiroysato/digdag-workflow-engine-link-collection-13hf) Please take a look.

**Comment by ehaupt** [comment]
Let's take your example. How would you tell digdag that the task `something.sh` has not finished with the desired result?

Would you use different exit codes

```
#!/bin/sh

do_something() {
        return 2
}

do_something
if [ $? = 0 ]; then
        echo "OK"
        exit 0
else    
        echo "FAILED"
        exit 2
fi      
```
rather set a variable in the environment store? For instance

`task1_status="FAILED"`

and then evaluate that variable from a different task? The verbosity of a != 0 exit code hints at the later.

**Comment by ehaupt** [comment]
Hello @hiroyuki-sato, my already composed reply just crossed your second reply and I think it confirms my a assumption that a task regardless of its result should always designed to exit with 0.

**Comment by hiroyuki-sato** [comment]
Hello, @ehaupt 

builtin `sh>` operator doesn't use the standard output as execution result parameter in your script.
If you want to use that, [digdag-plugin-shresult](https://github.com/takemikami/digdag-plugin-shresult) may help. (or use `py>` and `rb>` operator)

from your example. 

```bash
#!/bin/sh

do_something() {
        return 2
}

do_something
if [ $? = 0 ]; then
        echo "OK"
        exit 0
else    
        echo "FAILED"
        exit 2
fi      
```

```yaml
+task1:
  sh>: ./something.sh
  _error:
    +error_task:
      # This is just an example.
      # you can use slack>, mail> or something.
      echo>: "+task1 failed"

+task2:
  echo>: "task completed"
```

* If status code == 0: process `+task2`
* If status code == 2(not zero): process `+error_task` in `_error` part. (not process `+task2`)

**Comment by ehaupt** [comment]
Thank you for your excellent explanation.
