### ISSUE TITLE
[regression] --enable-swagger fails with Java 11 because java.se.ee was removed

### ISSUE THREAD

**Issue by ehaupt** [treasure-data/digdag#1611]
With Java 11 I noticed that running digdag with `--enable-swagger`fails with:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlRootElement
        at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:180)
        at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:127)
        at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:99)
        at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:106)
        at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:71)
        at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79)
        at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:58)
        at io.swagger.jaxrs.Reader.parseMethod(Reader.java:829)
        at io.swagger.jaxrs.Reader.read(Reader.java:298)
        at io.swagger.jaxrs.Reader.read(Reader.java:150)
        at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:235)
        at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:214)
        at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:229)
        at io.digdag.server.ServerModule.enableSwagger(ServerModule.java:158)
        at io.digdag.server.ServerModule.configure(ServerModule.java:91)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
        at com.google.inject.spi.Elements.getElements(Elements.java:103)
        at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:173)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
        at com.google.inject.spi.Elements.getElements(Elements.java:103)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at org.embulk.guice.Bootstrap.start(Bootstrap.java:168)
        at org.embulk.guice.Bootstrap.build(Bootstrap.java:130)
        at org.embulk.guice.Bootstrap.initializeCloseable(Bootstrap.java:125)
        at io.digdag.guice.rs.server.undertow.UndertowBootstrap.initialize(UndertowBootstrap.java:70)
        at io.digdag.guice.rs.GuiceRsServletContainerInitializer.processBootstrap(GuiceRsServletContainerInitializer.java:61)
        at io.digdag.guice.rs.GuiceRsServletContainerInitializer.onStartup(GuiceRsServletContainerInitializer.java:36)
        at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:192)
        at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:174)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:239)
        at io.digdag.guice.rs.server.undertow.UndertowServer.start(UndertowServer.java:186)
        at io.digdag.server.ServerBootstrap.start(ServerBootstrap.java:86)
        at io.digdag.cli.Server.startServer(Server.java:143)
        at io.digdag.cli.Server.main(Server.java:106)
        at io.digdag.cli.Main.cli(Main.java:195)
        at io.digdag.cli.Main.main(Main.java:83)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlRootElement
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 42 more
```

According to [this](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception) post it's because `java.se.ee` was removed in Java 11.

**Comment by ehaupt** [comment]
Close inactive issue.
