### ISSUE TITLE
[Regression] Commit breaks --enable-swagger

### ISSUE THREAD

**Issue by ehaupt** [treasure-data/digdag#1781]
~~[This](https://github.com/treasure-data/digdag/commit/5ef98b533e35cf483dc7b0662b3b9126911a4d8a) commit breaks~~ the server option `--enable-swagger`is currently broken with the following error:

```text
$ ./digdag-0.10.5-SNAPSHOT.jar server --enable-swagger
2023-01-10 11:59:41 +0100: Digdag v0.10.5-SNAPSHOT
2023-01-10 11:59:46 +0100 [INFO] (main): Reflections took 4482 ms to scan 1 urls, producing 55878 keys and 111228 values
Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedMember.getType(Lcom/fasterxml/jackson/databind/type/TypeBindings;)Lcom/fasterxml/jackson/databind/JavaType;
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:280)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:127)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:99)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:106)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:71)
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79)
	at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:58)
	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:829)
	at io.swagger.jaxrs.Reader.read(Reader.java:298)
	at io.swagger.jaxrs.Reader.read(Reader.java:150)
	at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:235)
	at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:214)
	at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:229)
	at io.digdag.server.ServerModule.enableSwagger(ServerModule.java:158)
	at io.digdag.server.ServerModule.configure(ServerModule.java:91)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:64)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)
	at com.google.inject.spi.Elements.getElements(Elements.java:108)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:214)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:64)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)
	at com.google.inject.spi.Elements.getElements(Elements.java:108)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:160)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at org.embulk.guice.Bootstrap.start(Bootstrap.java:168)
	at org.embulk.guice.Bootstrap.build(Bootstrap.java:130)
	at org.embulk.guice.Bootstrap.initializeCloseable(Bootstrap.java:125)
	at io.digdag.guice.rs.server.undertow.UndertowBootstrap.initialize(UndertowBootstrap.java:70)
	at io.digdag.guice.rs.GuiceRsServletContainerInitializer.processBootstrap(GuiceRsServletContainerInitializer.java:61)
	at io.digdag.guice.rs.GuiceRsServletContainerInitializer.onStartup(GuiceRsServletContainerInitializer.java:36)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:192)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:174)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:239)
	at io.digdag.guice.rs.server.undertow.UndertowServer.start(UndertowServer.java:180)
	at io.digdag.server.ServerBootstrap.start(ServerBootstrap.java:86)
	at io.digdag.cli.Server.startServer(Server.java:143)
	at io.digdag.cli.Server.main(Server.java:106)
	at io.digdag.cli.Main.cli(Main.java:198)
	at io.digdag.cli.Main.main(Main.java:86)
```

**EDIT**: Regression not tied to this particular commit.

**Comment by ehaupt** [comment]
This is now also broken in [v0.10.5](https://github.com/treasure-data/digdag/releases/tag/v0.10.5).

**Comment by ehaupt** [comment]
Error with 0.10.5:

```sh
# digdag server --enable-swagger --memory
2023-02-14 15:46:12 +0100: Digdag v0.10.5
2023-02-14 15:46:16 +0100 [INFO] (main): Reflections took 3225 ms to scan 1 urls, producing 56163 keys and 112271 values
Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedMember.getType(Lcom/fasterxml/jackson/databind/type/TypeBindings;)Lcom/fasterxml/jackson/databind/JavaType;
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:280)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:127)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:99)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:106)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:71)
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79)
	at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:58)
	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:829)
	at io.swagger.jaxrs.Reader.read(Reader.java:298)
	at io.swagger.jaxrs.Reader.read(Reader.java:150)
	at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:235)
	at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:214)
	at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:229)
	at io.digdag.server.ServerModule.enableSwagger(ServerModule.java:158)
	at io.digdag.server.ServerModule.configure(ServerModule.java:91)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:64)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)
	at com.google.inject.spi.Elements.getElements(Elements.java:108)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:214)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:64)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)
	at com.google.inject.spi.Elements.getElements(Elements.java:108)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:160)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at org.embulk.guice.Bootstrap.start(Bootstrap.java:168)
	at org.embulk.guice.Bootstrap.build(Bootstrap.java:130)
	at org.embulk.guice.Bootstrap.initializeCloseable(Bootstrap.java:125)
	at io.digdag.guice.rs.server.undertow.UndertowBootstrap.initialize(UndertowBootstrap.java:70)
	at io.digdag.guice.rs.GuiceRsServletContainerInitializer.processBootstrap(GuiceRsServletContainerInitializer.java:61)
	at io.digdag.guice.rs.GuiceRsServletContainerInitializer.onStartup(GuiceRsServletContainerInitializer.java:36)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:192)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:174)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:239)
	at io.digdag.guice.rs.server.undertow.UndertowServer.start(UndertowServer.java:180)
	at io.digdag.server.ServerBootstrap.start(ServerBootstrap.java:86)
	at io.digdag.cli.Server.startServer(Server.java:143)
	at io.digdag.cli.Server.main(Server.java:106)
	at io.digdag.cli.Main.cli(Main.java:198)
	at io.digdag.cli.Main.main(Main.java:86)
```

**Comment by ehaupt** [comment]
Superseded by https://github.com/treasure-data/digdag/issues/1791
