### ISSUE TITLE
Using ${td.last_results.job_count} causes an error with --dry-run

### ISSUE THREAD

**Issue by xerial** [treasure-data/digdag#18]
```
$ digdag run -d
...
2016-03-11 21:27:04 +0900 [ERROR] (0021@+main+tfidf): Task failed
java.lang.RuntimeException: Failed to process task config templates
    at io.digdag.core.agent.OperatorManager.runWithArchive(OperatorManager.java:156)
    at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$1(OperatorManager.java:128)
    at io.digdag.core.agent.CurrentDirectoryArchiveManager.withExtractedArchive(CurrentDirectoryArchiveManager.java:20)
    at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:127)
    at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:106)
    at io.digdag.cli.Run$OperatorManagerWithSkip.run(Run.java:567)
    at io.digdag.core.agent.LocalAgent.lambda$run$0(LocalAgent.java:61)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: io.digdag.spi.TemplateException: Failed to evaluate JavaScript code: ${td.last_results.job_count}
```

**Comment by frsyuki** [comment]
This is difficult to solve by the current design of dry-run. Because parameters are run-time information, dry-run can't evaluate all parameters. Therefore, what it can is just showing order of execution and templates without evaluation. This is not dry-run, but a sort of visualizations.

So, digdag will remove dry-run, and add another subcommand that shows execution order and parameters (without total evaluation) visually.

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
