### ISSUE TITLE
for_each parameterization capability is limited

### ISSUE THREAD

**Issue by danielnorberg** [treasure-data/digdag#25]
`for_each>` parameters can be parameterized like below by utilizing YAML anchors:

```yaml
run: +parameterized_for_each

_export:
  foos: &FOOS
    - 1
    - 2

+parameterized_for_each:
  for_each>:
    foo: *FOOS
  _do:
    sh>: "echo hello ${foo}"
```

But it might be useful to allow for parameterizing `for_each>` using actual digdag parameters. E.g.

```yaml
run: +parameterized_for_each

_export:
  foos:
    - 1
    - 2

+parameterized_for_each:
  for_each>:
    foo: @foos
  _do:
    sh>: "echo hello ${foo}"
```

And using parameters explicitly set by e.g. a `py>` task:

```yaml
run: +main

+main:
  +export_foos:
    py>: tasks.export_foos
  +parameterized_for_each:
    for_each>:
      foo: ${foos}
    _do:
      sh>: "echo hello ${foo}"
```

```python
import digdag

def export_foos():
    digdag.env.store({"foos": [1, 2]})
```

Attempting to parameterize `for_each>` like this currently fails with the below error:

```
2016-03-30 10:18:17 +0900: Digdag v0.4.2
2016-03-30 10:18:18 +0900 [WARN] (main): Reusing the last session time 2016-03-29T00:00:00+09:00.
2016-03-30 10:18:18 +0900 [INFO] (main): Using session digdag.status/20160329T000000+0900.
2016-03-30 10:18:18 +0900 [INFO] (main): Starting a new session repository id=1 workflow name=+main session_time=2016-03-29T00:00:00+09:00
2016-03-30 10:18:19 +0900 [INFO] (0020@+main+export_foos): py>: tasks.export_foos
2016-03-30 10:18:19 +0900 [INFO] (0020@+main+parameterized_for_each): for_each>: {foo=[1,2]}
2016-03-30 10:18:19 +0900 [ERROR] (0020@+main+parameterized_for_each): Task failed
io.digdag.client.config.ConfigException: Expected array type for key 'foo' but got "[1,2]" (string)
	at io.digdag.client.config.Config.propagateConvertException(Config.java:400)
	at io.digdag.client.config.Config.readObject(Config.java:391)
	at io.digdag.client.config.Config.get(Config.java:235)
	at io.digdag.client.config.Config.getList(Config.java:277)
	at io.digdag.standards.operator.ForEachOperatorFactory$ForEachOperator.runTask(ForEachOperatorFactory.java:67)
	at io.digdag.standards.operator.BaseOperator.run(BaseOperator.java:49)
	at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:238)
	at io.digdag.cli.Run$OperatorManagerWithSkip.callExecutor(Run.java:653)
	at io.digdag.core.agent.OperatorManager.runWithArchive(OperatorManager.java:193)
	at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$1(OperatorManager.java:130)
	at io.digdag.core.agent.CurrentDirectoryArchiveManager.withExtractedArchive(CurrentDirectoryArchiveManager.java:20)
	at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:129)
	at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:107)
	at io.digdag.cli.Run$OperatorManagerWithSkip.run(Run.java:635)
	at io.digdag.core.agent.LocalAgent.lambda$run$0(LocalAgent.java:61)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token
 at [Source: N/A; line: -1, column: -1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:854)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:850)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:292)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:227)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3703)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2072)
	at io.digdag.client.config.Config.readObject(Config.java:388)
	... 18 common frames omitted
error:
  * +main+parameterized_for_each:
    Expected array type for key 'foo' but got "[1,2]" (string)

Task state is saved at digdag.status/20160329T000000+0900 directory.
Run command with --session '2016-03-29 00:00:00' argument to retry failed tasks.
```

I'm uncertain whether the best approach would be to make `${...}` expansion more intelligent about types of parameters and not coerce everything to a string, or if it would make more sense to introduce another syntax.

**Comment by frsyuki** [comment]
How about using `!array` and `!map`?

```yaml
+expand_array:
  # "tables" is set using -p 'tables=["a", "b"]'
  for_each>:
    table: !array ${tables}

+expand_map:
  # "my_account" is set using -p 'my_account={"apikey": "mykey"}'
  _export:
    td: !map ${my_account}
  +query:
    td>: ...
```
