### ISSUE TITLE
[feature-request] rb operator supports bundler

### ISSUE THREAD

**Issue by toru-takahashi** [treasure-data/digdag#318]
Currently, Digdag’s rb operator doesn’t seem to be able to use bundler.
https://github.com/treasure-data/digdag/blob/b557732d556a0adc900e6d9f90ae7d49fb4731ff/digdag-standards/src/main/java/io/digdag/standards/operator/RbOperatorFactory.java#L129-L129

We would like to use bundle exec on ruby operator.
Because, we want to avoid installing library to global.

We want digdag to supports bundler for rb operator.

**Comment by toru-takahashi** [comment]
Current workaround is to use bundler/inline.
Ref. http://qiita.com/satoruk/items/3e4c47eb0edabbeafee5

```
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "oj"
end

class TestBundle
  def foo
    p Oj.dump(hello: "hi")
  end
end
```

```
$ less test_bundle.dig
timezone: Asia/Tokyo

_export:
  rb:
    require: "tasks/test_bundle"

+step1:
  rb>: TestBundle.foo
```

```
$ digdag run test_bundle.dig --rerun
2016-07-15 19:16:22 +0900: Digdag v0.8.3
2016-07-15 19:16:23 +0900 [WARN] (main): Reusing the last session time 2016-07-15T00:00:00+09:00.
2016-07-15 19:16:23 +0900 [INFO] (main): Using session .digdag/status/20160715T000000+0900.
2016-07-15 19:16:23 +0900 [INFO] (main): Starting a new session project id=1 workflow name=test_bundle session_time=2016-07-15T00:00:00+09:00
2016-07-15 19:16:23 +0900 [INFO] (0018@+test_bundle+step1): rb>: TestBundle.foo
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Resolving dependencies...
Using bundler 1.12.5
Installing oj 2.17.1 with native extensions
"{\":hello\":\"hi\"}"
Success. Task state is saved at .digdag/status/20160715T000000+0900 directory.
  * Use --session <daily | hourly | "yyyy-MM-dd[ HH:mm:ss]"> to not reuse the last session time.
  * Use --rerun, --start +NAME, or --goal +NAME argument to rerun skipped tasks.
```

**Comment by frsyuki** [comment]
`require "bundler/setup` or `Bundler.setup ` is a documented way: http://bundler.io/bundler_setup.html

Idea 1: use Docker and global ruby:

```
_export:
  docker:
    image: YOUR_IMAGE_WITH_RBENV
    build:
      - gem install bundler
      - bundle install
  rb:
    require: lib/your_init_script

+task:
  rb>: MyClass.foobar
```

Python will use the same way:

```
_export:
  docker:
    image: YOUR_IMAGE_WITH_PYENV
    build:
      - pip install -r requirements.txt

+task:
  py>: my.MyClass.foobar
```

Idea 2: Convention over Configuration A: if Gemfile.lock file exists, automatically runs `bundle exec ruby` instead of `ruby`

Idea 3: Convention over Configuration B: if `init.rb` file exists, digdag automatically requires it. And documents recommend to have following lines in it:

```
require 'bundler/setup'
require 'your_class_def_files'
```

Idea 4: Convention over Configuration C: if Gemfile.lock file exists, automatically runs `bundle exec ruby` instead of `ruby`. In addition to it, if `rb/*.rb` files exist (such as `rb/my_class.rb`), digdag automatically requires all of them.

Idea 5: allow customization of command line:

```
_export:
  rb:
    ruby: [bundle, exec, ruby, -r, init.rb]  # new option
```

**Comment by frsyuki** [comment]
@toru-takahashi which ideas do you think better/worse in your opinion?

**Comment by toru-takahashi** [comment]
It looks idea2 is simple and good.
On the other hands, ruby and python should be able to do same usage.
So, idea1 is useful for a expert digdag users.

**Comment by y-ken** [comment]
Thank you very much. I feel good to have idea2 for light digdag user. because it is very simple.
Of course, idea 1 is useful to solve dependency problems for production.

**Comment by grezar** [comment]
Hi.
I tried idea1 and it didn't work.
I defined a workflow like below

```
_export:
  docker:
    image: ruby:latest
    build: ["bundle install"]
  rb:
    require: task/my_workflow

+setup:
  +start:
    echo>: start ${session_time}

+task1:
  rb>: Task::MyWorkflow.step1
```
and place Gemfile in project root
```
$ tree
project
├── Gemfile
├── my_worklow.dig
└── task
    └── my_workflow.rb
```
then run workflow with local mode
```
$ digdag run my_workflow.dig
2018-05-08 18:33:21 +0900: Digdag v0.9.24
2018-05-08 18:33:23 +0900 [WARN] (main): Using a new session time 2018-05-08T00:00:00+00:00.
2018-05-08 18:33:23 +0900 [INFO] (main): Using session /Users/grezar/workspace/project/.digdag/status/20180508T000000+0000.
2018-05-08 18:33:23 +0900 [INFO] (main): Starting a new session project id=1 workflow name=project session_time=2018-05-08T00:00:00+00:00
2018-05-08 18:33:24 +0900 [INFO] (0018@[0:default]+project+setup+start): echo>: start 2018-05-08T00:00:00+00:00
start 2018-05-08T00:00:00+00:00
2018-05-08 18:33:24 +0900 [INFO] (0018@[0:default]+project+task1): rb>: Task::MyWorkflow.step1
2018-05-08 18:33:24 +0900 [INFO] (0018@[0:default]+project+task1): Building docker image digdag-project-1:7a81509fa33496f7678137f6d4e917fe759d9bf4
Sending build context to Docker daemon  13.31kB
Step 1/2 : FROM ruby:latest
 ---> fb664b54b956
Step 2/2 : RUN bundle install
 ---> Running in b6764606f127
Could not locate Gemfile
Removing intermediate container b6764606f127
The command '/bin/sh -c bundle install' returned a non-zero code: 10
2018-05-08 18:33:26 +0900 [ERROR] (0018@[0:default]+project+task1): Task failed with unexpected error: Docker build failed
java.lang.RuntimeException: Docker build failed
	at io.digdag.standards.command.DockerCommandExecutor.buildImage(DockerCommandExecutor.java:232)
	at io.digdag.standards.command.DockerCommandExecutor.startWithDocker(DockerCommandExecutor.java:69)
	at io.digdag.standards.command.DockerCommandExecutor.start(DockerCommandExecutor.java:53)
	at io.digdag.standards.operator.RbOperatorFactory$RbOperator.runCode(RbOperatorFactory.java:147)
	at io.digdag.standards.operator.RbOperatorFactory$RbOperator.runTask(RbOperatorFactory.java:92)
	at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
	at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:312)
	at io.digdag.cli.Run$OperatorManagerWithSkip.callExecutor(Run.java:694)
	at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:254)
	at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137)
	at io.digdag.core.agent.LocalWorkspaceManager.withExtractedArchive(LocalWorkspaceManager.java:25)
	at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135)
	at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119)
	at io.digdag.cli.Run$OperatorManagerWithSkip.run(Run.java:676)
	at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-05-08 18:33:26 +0900 [INFO] (0018@[0:default]+project^failure-alert): type: notify
error:
  * +project+task1:
    Docker build failed (runtime)

Task state is saved at /Users/grezar/workspace/project/.digdag/status/20180508T000000+0000 directory.
  * Use --session <daily | hourly | "yyyy-MM-dd[ HH:mm:ss]"> to not reuse the last session time.
  * Use --rerun, --start +NAME, or --goal +NAME argument to rerun skipped tasks.
```

It seems that bundle install is executed at not digdag workspace (which is created at runtime), but container workdir.

**Comment by sonots-zozo** [comment]
+1 for `bundle exec`.

**Comment by sonots-zozo** [comment]
Let me note about a current (0.9.33) possible way to use bundler.

(w/o _export: docker:)

```
+task:
  _env:
    BUNDLE_GEMFILE: /path/to/Gemfile
  rb>: Workflow.foo
  require: tasks/workflow
```

tasks/workflow.rb

```
require 'bundler/setup'
```

(w/ _export: docker:)

```
+task:
  _export:
    docker:
      image: your_image_bundle_installed_inside
  _env:
    BUNDLE_GEMFILE: /path/to/Gemfile/in/docker
  rb>: Workflow.foo
  require: tasks/workflow
```

tasks/workflow.rb

```
require 'bundler/setup'
```

I dislike to write `require 'bundler/setup'` to each task file, though.

--------

Also, I tried to use `RUBYOPT=-rbundler/setup` environment variable, but it did not work well because ruby loads `-r` option before `RUBYOPOT`. https://bugs.ruby-lang.org/issues/5445

(this does not work)
```
+task:
  _export:
    docker:
      image: your_image_bundle_installed_inside
  _env:
    BUNDLE_GEMFILE: /path/to/Gemfile/in/docker
    RUBYOPT: "-rbundler/setup"
  rb>: Workflow.foo
  require: tasks/workflow
```

`digdag` rb operator runs ruby like `ruby -r tasks/workflow`

**Comment by sonots-zozo** [comment]
@hiroyuki-sato told me that digdag >= 0.9.33 allows to specify ruby command, so we can:

bundle_exec_ruby.sh

```
#!/bin/bash

exec bundle exec ruby $*
```

sample.dig

```
+task:
  _export:
    rb:
      ruby: /path/to/bundle_exec_ruby.sh
  rb>: Workflow.foo
  require: tasks/workflow
```

as long as digdag working directory has `Gemfile`, `Gemfile.lock`, `.bundle/config`.

**Comment by sonots-zozo** [comment]
To make it better https://github.com/treasure-data/digdag/issues/318#issuecomment-466006823, my preference is that:

Idea6: Support multiple require(s) or global require:

```
+task:
  _export:
    docker:
      image: your_image_bundle_installed_inside
  _env:
    BUNDLE_GEMFILE: /path/to/Gemfile/in/docker
  rb>: Workflow.foo
  requires:
    - bundler/setup
    - tasks/workflow
```

Idea7: Support ruby custom options:

```
+task:
  _export:
    docker:
      image: your_image_bundle_installed_inside
    rb:
      option: "-rbundler/setup"
  _env:
    BUNDLE_GEMFILE: /path/to/Gemfile/in/docker
  rb>: Workflow.foo
  require: tasks/workflow
```

**Comment by sonots-zozo** [comment]
At a first glance,

Idea 5: allow customization of command line:

```yaml
_export:
  rb:
    ruby: [bundle, exec, ruby, -r, init.rb]  # new option
```

looks good, but this requires `Gemfile`, `Gemfile.lock`, `.bundle/config` are located at the working directory, and thus, it is not suitable for `_export: docker:` option.

I mean that, assume we locate these files at `/var/lib/ruby` inside a docker container. Because digdag mounts project root to the docker working directory, we have to chdir to `/var/lib/ruby` to run `bundle exec`, but Idea5 does not have a way to do it.

**Comment by sonots-zozo** [comment]
With >= 0.9.35:

Idea 5: allow customization of command line:

```
+task:
  _export:
    docker:
      image: your_image_bundle_installed_inside
    rb:
      ruby: [ruby, -rbundler/setup]
  _env:
    BUNDLE_GEMFILE: /path/to/Gemfile/in/docker
  rb>: Workflow.foo
  require: tasks/workflow
```

is now possible.

**Comment by yoyama** [comment]
@toru-takahashi I close this issue because of PR#1022 may fix this issue. Feel free to re-open if need.
