### ISSUE TITLE
spurious LambdaForm ClassCastException

### ISSUE THREAD

**Issue by danielnorberg** [treasure-data/digdag#391]
Tried to repro but was not successful.

The only way I can think of to handle JVM bugs is to crash and restart when necessary. I believe this is another good reason to run operators in separate short-lived processes.

https://travis-ci.org/treasure-data/digdag/jobs/176305535

https://bugs.openjdk.java.net/browse/JDK-8145371

[log.txt](https://github.com/treasure-data/digdag/files/596435/log.txt)

```
acceptance.BuiltInVariablesIT > testRun STANDARD_OUT
    2016-11-16 08:44:29 +0000 [ERROR] (0020@+built_in_variables+get_variables+timezone) io.digdag.core.agent.OperatorManager: Task failed with unexpected error: Failed to process variables
    java.lang.RuntimeException: Failed to process variables
    	at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:208)
    	at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:141)
    	at io.digdag.core.agent.LocalWorkspaceManager.withExtractedArchive(LocalWorkspaceManager.java:25)
    	at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:139)
    	at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:123)
    	at io.digdag.cli.Run$OperatorManagerWithSkip.run(Run.java:660)
    	at io.digdag.core.agent.MultiThreadAgent.lambda$run$0(MultiThreadAgent.java:95)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.ClassCastException: java.lang.invoke.LambdaForm cannot be cast to [Ljava.lang.invoke.LambdaFormEditor$Transform;
    	at java.lang.invoke.LambdaFormEditor.getInCache(LambdaFormEditor.java:275)
    	at java.lang.invoke.LambdaFormEditor.filterArgumentForm(LambdaFormEditor.java:635)
    	at java.lang.invoke.MethodHandles.filterArgument(MethodHandles.java:2618)
    	at java.lang.invoke.MethodHandles.filterArguments(MethodHandles.java:2606)
    	at jdk.nashorn.internal.lookup.MethodHandleFactory$StandardMethodHandleFunctionality.filterArguments(MethodHandleFactory.java:383)
    	at jdk.nashorn.internal.runtime.WithObject.filterReceiver(WithObject.java:324)
    	at jdk.nashorn.internal.runtime.WithObject.fixScopeCallSite(WithObject.java:300)
    	at jdk.nashorn.internal.runtime.WithObject.lookup(WithObject.java:132)
    	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:104)
    	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:98)
    	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
    	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
    	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
    	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
    	at jdk.nashorn.internal.scripts.Script$Recompilation$645$13$\^function\_.L:1(<function>:3)
    	at jdk.nashorn.internal.scripts.Script$Recompilation$612$62AA$\^eval\_.template(<eval>:56)
    	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:641)
    	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
    	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
    	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
    	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:383)
    	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
    	at io.digdag.core.agent.ConfigEvalEngine.invokeTemplate(ConfigEvalEngine.java:112)
    	at io.digdag.core.agent.ConfigEvalEngine.access$200(ConfigEvalEngine.java:30)
    	at io.digdag.core.agent.ConfigEvalEngine$Context.evalValue(ConfigEvalEngine.java:205)
    	at io.digdag.core.agent.ConfigEvalEngine$Context.evalObjectRecursive(ConfigEvalEngine.java:163)
    	at io.digdag.core.agent.ConfigEvalEngine$Context.access$000(ConfigEvalEngine.java:132)
    	at io.digdag.core.agent.ConfigEvalEngine.eval(ConfigEvalEngine.java:78)
    	at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:199)
    	... 11 common frames omitted
```

**Comment by yoyama** [comment]
The JDK issue has been already closed.
So I close this issue.
