### ISSUE TITLE
Help with building DigDag

### ISSUE THREAD

**Issue by nqbao** [treasure-data/digdag#509]
Hi, 

I am trying to build digdag on my laptop (Mac) but I keep getting this error when trying to access `gradlew tasks`

```
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_wa0ajp14gh42ykod5uuew4p5$_run_closure2.doCall(/digdag/build.gradle:243)
Publication mavenJava not found in project :.
Publication mavenJava not found in project :digdag-docs.
Publication mavenJava not found in project :digdag-ui.
:tasks

------------------------------------------------------------
All tasks runnable from root project
------------------------------------------------------------

:tasks FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tasks'.
> Could not determine the dependencies of task ':digdag-spi:bintrayUpload'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.442 secs
```

When i tried to run with `--stacktrace`, it is yielding me 

```
Caused by: org.gradle.api.UnknownTaskException: Task with path 'publishMavenJavaPublicationToMavenLocal' not found in project ':digdag-client'.
	at org.gradle.api.internal.tasks.DefaultTaskContainer.getByPath(DefaultTaskContainer.java:177)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.resolveTask(DefaultTaskContainer.java:159)
	at org.gradle.api.internal.tasks.DefaultTaskDependency.visitDependencies(DefaultTaskDependency.java:108)
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:88)
	at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmpyEdges.getNodeValues(CachingDirectedGraphWalker.java:202)
	at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:112)
	at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:64)
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.doResolve(CachingTaskDependencyResolveContext.java:76)
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.resolve(CachingTaskDependencyResolveContext.java:65)
	... 89 more
```

I did try google around but no clue. I am and using gradle 3.21 and mvn 3.3.9. I'm also kinda new to Java. Can you help me solve this problem? Much appreciate.

**Comment by hiroyuki-sato** [comment]
Hello @nqbao 

If you want to build digdag command by yourself, please try `./gradlew cli` command.
When the build complete, you will find digdag-x.y.z-SNAPSHOT.jar in pkg directory. 
It is an executable binary. 

```
./pkg/digdag-0.9.6-SNAPSHOT.jar
2017-03-14 14:39:06 +0900: Digdag v0.9.6-SNAPSHOT
Usage: digdag <command> [options...]
  Local-mode commands:
    init <dir>                         create a new workflow project
    r[un] <workflow.dig>               run a workflow
    c[heck]                            show workflow definitions
    sched[uler]                        run a scheduler server
    selfupdate                         update cli to the latest version

  Server-mode commands:
    server                             start serv
```

**Comment by nqbao** [comment]
Thanks! It worked! I also found that `./gradlew build` also work the.

Just wonder why `./gradew tasks` does not work? Does it suppose to show me all available tasks under the projecT?

**Comment by hiroyuki-sato** [comment]
I'm not familiar `Gradle` 😅.  But It may be a misconfiguration in build.gradle. 
Please close this issue. I made #510 (It's better 'title' than this issue)

**Comment by nqbao** [comment]
Yeah, thanks for helping on this!
