### ISSUE TITLE
java.lang.IllegalStateException: Not in transaction occured when I execute digdag scheduler.

### ISSUE THREAD

**Issue by k2jpm90dzl** [treasure-data/digdag#551]
I cannot run `digdag scheduler`.
When I execute job with scheduler when `java.lang.IllegalStateException` occured.
I would like to know how to execute it.
I have followed [Getting started](http://docs.digdag.io/getting_started.html) page and have installed digdag and set up as below.

- Initialize project

```
$ digdag init workflow
$ cd workflow
```

- Edit the workflow definition as bellow.

```yml
$ cat workflow.dig
timezone: UTC
  
schedule:
  minutes_interval>: 1

+step1:
  echo>: 'This is step 1.'

+step2:
  echo>: 'This is step 2. Hello, world!'
```

- Execute jobs

```c
$ digdag run workflow.dig
2017-04-28 14:57:47 +0900: Digdag v0.9.10
2017-04-28 14:57:48 +0900 [WARN] (main): Using a new session time 2017-04-28T05:57:00+00:00 based on schedule.
2017-04-28 14:57:48 +0900 [INFO] (main): Using session /Users/xxxxx/development/workspaces/digdag/workflow/.digdag/status/20170428T055700+0000.
2017-04-28 14:57:48 +0900 [INFO] (main): Starting a new session project id=1 workflow name=workflow session_time=2017-04-28T05:57:00+00:00
2017-04-28 14:57:50 +0900 [INFO] (0017@[0:default]+workflow+step1): echo>: This is step 1.
This is step 1.
2017-04-28 14:57:50 +0900 [INFO] (0017@[0:default]+workflow+step2): echo>: This is step 2. Hello, world!
This is step 2. Hello, world!
Success. Task state is saved at /Users/xxxxx/development/workspaces/digdag/workflow/.digdag/status/20170428T055700+0000 directory.
  * Use --session <daily | hourly | "yyyy-MM-dd[ HH:mm:ss]"> to not reuse the last session time.
  * Use --rerun, --start +NAME, or --goal +NAME argument to rerun skipped tasks.
```

- Run scheduled jobs. (Then, exception occured. `java.lang.IllegalStateException: Not in transaction`)

```c
$ digdag scheduler
2017-04-28 14:58:00 +0900: Digdag v0.9.10
2017-04-28 14:58:02 +0900 [INFO] (main): secret encryption engine: disabled
Exception in thread "main" java.lang.Error: java.lang.reflect.InvocationTargetException
	at org.embulk.guice.LifeCycleModule$1$1.afterInjection(LifeCycleModule.java:81)
	at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:115)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at org.embulk.guice.Bootstrap.start(Bootstrap.java:155)
	at org.embulk.guice.Bootstrap.build(Bootstrap.java:117)
	at org.embulk.guice.Bootstrap.initializeCloseable(Bootstrap.java:112)
	at io.digdag.guice.rs.server.undertow.UndertowBootstrap.initialize(UndertowBootstrap.java:70)
	at io.digdag.guice.rs.GuiceRsServletContainerInitializer.processBootstrap(GuiceRsServletContainerInitializer.java:61)
	at io.digdag.guice.rs.GuiceRsServletContainerInitializer.onStartup(GuiceRsServletContainerInitializer.java:36)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:186)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:171)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:234)
	at io.digdag.guice.rs.server.undertow.UndertowServer.start(UndertowServer.java:179)
	at io.digdag.server.ServerBootstrap.start(ServerBootstrap.java:73)
	at io.digdag.cli.Sched.startScheduler(Sched.java:108)
	at io.digdag.cli.Sched.main(Sched.java:55)
	at io.digdag.cli.Main.cli(Main.java:187)
	at io.digdag.cli.Main.main(Main.java:82)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.embulk.guice.LifeCycleManager.startInstance(LifeCycleManager.java:203)
	at org.embulk.guice.LifeCycleManager.addInstance(LifeCycleManager.java:185)
	at org.embulk.guice.LifeCycleModule$1$1.afterInjection(LifeCycleModule.java:78)
	... 33 more
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Not in transaction
	at io.digdag.cli.Sched$RevisionAutoReloaderStarter.start(Sched.java:158)
	... 40 more
Caused by: java.lang.IllegalStateException: Not in transaction
	at io.digdag.core.database.ThreadLocalTransactionManager.getHandle(ThreadLocalTransactionManager.java:212)
	at io.digdag.core.database.BasicDatabaseStoreManager.transaction(BasicDatabaseStoreManager.java:191)
	at io.digdag.core.database.BasicDatabaseStoreManager.transaction(BasicDatabaseStoreManager.java:171)
	at io.digdag.core.database.DatabaseProjectStoreManager$DatabaseProjectStore.putAndLockProject(DatabaseProjectStoreManager.java:179)
	at io.digdag.core.LocalSite.storeLocalWorkflowsImpl(LocalSite.java:98)
	at io.digdag.core.LocalSite.storeLocalWorkflows(LocalSite.java:136)
	at io.digdag.cli.RevisionAutoReloader$ReloadTarget.storeProject(RevisionAutoReloader.java:131)
	at io.digdag.cli.RevisionAutoReloader$ReloadTarget.<init>(RevisionAutoReloader.java:120)
	at io.digdag.cli.RevisionAutoReloader$ReloadTarget.<init>(RevisionAutoReloader.java:108)
	at io.digdag.cli.RevisionAutoReloader.watch(RevisionAutoReloader.java:72)
	at io.digdag.cli.Sched$RevisionAutoReloaderStarter.start(Sched.java:155)
	... 40 more
```

Do I have to set up any files more? Or is my job definition wrong?

### Environment

Mac OS X El Captitan
Digdag v0.9.10
Java runtime version is "1.8.0_102"

Thank you.

**Comment by frsyuki** [comment]
#555 fixes this issue. It will be included in the next release which will be there soon.

**Comment by k2jpm90dzl** [comment]
Thank you for fixing this issue quickly. I'm looking forward to being released next fixed version. :)
