### ISSUE TITLE
FileSystemException on Docker container

### ISSUE THREAD

**Issue by koooge** [treasure-data/digdag#585]
Hello.
I caught following FileSystemException on Docker container.

```
$ docker exec 6dd java -jar /usr/local/bin/digdag run /mydag.dig
2017-06-23 06:54:52 +0000: Digdag v0.9.12
error: java.nio.file.FileSystemException: /proc/self/task/178/fd/24/proc/self/task/178/fd/24/proc/self/task/178/fd/24/proc/self/task/178/fd/24/proc/self/task/178/fd/24/proc/self/task/178/fd/24/proc/self/task/178/fd/24/proc/self/task/178/fd/24/proc/self/task/178/fd/24/proc/self/task/178/fd/24/proc/self/task/178/fd/24/proc/self/task/178/fd/24/proc/self/task/178/fd/24/proc/self/task/178/fd/24/proc/self/task/178/fd/24/proc/self/task/178/fd/24/proc/self/task/178/fd/24/proc/self/task/178/fd/24/proc/self/task/178/fd/24/proc/self/task/178/fd/24/proc/1/map_files: Operation not permitted (directory iterator)
```

my environment: https://github.com/koooge/docker-recipes/tree/digdag/digdag-embulk
It seems that it also does'nt work `digdag schedular`

**Comment by koooge** [comment]
log of `java -jar /usr/local/bin/digdag scheduler`

```
2017-06-23 03:18:15 +0000: Digdag v0.9.12
2017-06-23 03:18:20 +0000 [INFO] (main) io.digdag.core.crypto.SecretCryptoProvider: secret encryption engine: disabled
Exception in thread "main" java.lang.Error: java.lang.reflect.InvocationTargetException
	at org.embulk.guice.LifeCycleModule$1$1.afterInjection(LifeCycleModule.java:81)
	at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:115)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at org.embulk.guice.Bootstrap.start(Bootstrap.java:155)
	at org.embulk.guice.Bootstrap.build(Bootstrap.java:117)
	at org.embulk.guice.Bootstrap.initializeCloseable(Bootstrap.java:112)
	at io.digdag.guice.rs.server.undertow.UndertowBootstrap.initialize(UndertowBootstrap.java:70)
	at io.digdag.guice.rs.GuiceRsServletContainerInitializer.processBootstrap(GuiceRsServletContainerInitializer.java:61)
	at io.digdag.guice.rs.GuiceRsServletContainerInitializer.onStartup(GuiceRsServletContainerInitializer.java:36)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:186)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:171)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:234)
	at io.digdag.guice.rs.server.undertow.UndertowServer.start(UndertowServer.java:179)
	at io.digdag.server.ServerBootstrap.start(ServerBootstrap.java:73)
	at io.digdag.cli.Sched.startScheduler(Sched.java:108)
	at io.digdag.cli.Sched.main(Sched.java:55)
	at io.digdag.cli.Main.cli(Main.java:187)
	at io.digdag.cli.Main.main(Main.java:82)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.embulk.guice.LifeCycleManager.startInstance(LifeCycleManager.java:203)
	at org.embulk.guice.LifeCycleManager.addInstance(LifeCycleManager.java:185)
	at org.embulk.guice.LifeCycleModule$1$1.afterInjection(LifeCycleModule.java:78)
	... 33 more
Caused by: java.lang.RuntimeException: java.nio.file.DirectoryIteratorException: java.nio.file.FileSystemException: /proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/1/map_files: Operation not permitted
	at io.digdag.cli.Sched$RevisionAutoReloaderStarter.start(Sched.java:158)
	... 40 more
Caused by: java.nio.file.DirectoryIteratorException: java.nio.file.FileSystemException: /proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/1/map_files: Operation not permitted
	at sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:172)
	at sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.hasNext(UnixDirectoryStream.java:201)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:97)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFilesRecursively(ProjectArchive.java:102)
	at io.digdag.core.archive.ProjectArchive.listFiles(ProjectArchive.java:66)
	at io.digdag.core.archive.ProjectArchiveLoader.load(ProjectArchiveLoader.java:40)
	at io.digdag.cli.Arguments.loadProject(Arguments.java:100)
	at io.digdag.cli.Sched$RevisionAutoReloaderStarter.start(Sched.java:154)
	... 40 more
Caused by: java.nio.file.FileSystemException: /proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/self/task/1/fd/24/proc/1/map_files: Operation not permitted
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.asIOException(UnixException.java:111)
	at sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:171)
	... 169 more
```

**Comment by hiroyuki-sato** [comment]
@koooge 

I'll try to investigate this issue. 

* Does this error reproduce without docker? or docker only issue?
* Did you setup server secrets? http://docs.digdag.io/command_reference.html#secret-encryption-key
  * I'm not sure but I saw `io.digdag.core.crypto.SecretCryptoProvider` Is it secret related?

**Comment by koooge** [comment]
@hiroyuki-sato san

> - Does this error reproduce without docker? or docker only issue?
In my environment, it occurs only in the docker container.

result on debian8 🆗 

```
vagrant@debian:~/docker-recipes/digdag-embulk$ digdag run mydag.dig
2017-06-23 21:07:53 +0200: Digdag v0.9.12
2017-06-23 21:07:56 +0200 [WARN] (main): Using a new session time 2017-06-24T04:07:00+09:00 based on schedule.
2017-06-23 21:07:56 +0200 [INFO] (main): Using session /home/vagrant/docker-recipes/digdag-embulk/.digdag/status/20170624T040700+0900.
2017-06-23 21:07:56 +0200 [INFO] (main): Starting a new session project id=1 workflow name=mydag session_time=2017-06-24T04:07:00+09:00
2017-06-23 21:07:58 +0200 [INFO] (0016@[0:default]+mydag+task): embulk>: config.yml
2017-06-23 21:08:04.844 +0200: Embulk v0.8.21
2017-06-23 21:08:08.118 +0200 [INFO] (0001:transaction): Listing local files at directory '.' filtering filename by prefix 'test.csv'
2017-06-23 21:08:08.131 +0200 [INFO] (0001:transaction): "follow_symlinks" is set false. Note that symbolic links to directories are skipped.
2017-06-23 21:08:08.133 +0200 [INFO] (0001:transaction): Loading files [test.csv]
2017-06-23 21:08:08.271 +0200 [INFO] (0001:transaction): Using local thread executor with max_threads=2 / tasks=1
2017-06-23 21:08:08.293 +0200 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2017-06-23 21:08:08.551 +0200 [WARN] (0014:task-0000): Skipped line 2 (java.lang.NumberFormatException: For input string: "# comment line"): # comment line
2017-06-23 21:08:08.560 +0200 [WARN] (0014:task-0000): Skipped line 5 (Too many columns): 1005, "foo,bar\.piyo",,
2017-06-23 21:08:08.561 +0200 [WARN] (0014:task-0000): Skipped line 6 (java.lang.NumberFormatException: For input string: "## coment line"): ## coment line
2017-06-23 21:08:08.561 +0200 [WARN] (0014:task-0000): Skipped line 7 (Too many columns): 444444444, ""12345"", """123,45""", 12345
1004, hoge, 12ffe, 2554
1006, fuga1, fgr@7-, -46uaf
2017-06-23 21:08:08.562 +0200 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2017-06-23 21:08:08.567 +0200 [INFO] (main): Committed.
2017-06-23 21:08:08.568 +0200 [INFO] (main): Next config diff: {"in":{"last_path":"test.csv"},"out":{}}

Success. Task state is saved at /home/vagrant/docker-recipes/digdag-embulk/.digdag/status/20170624T040700+0900 directory.
  * Use --session <daily | hourly | "yyyy-MM-dd[ HH:mm:ss]"> to not reuse the last session time.
  * Use --rerun, --start +NAME, or --goal +NAME argument to rerun skipped tasks.
```

> - Did you setup server secrets? http://docs.digdag.io/command_reference.html#secret-encryption-key
>     - I'm not sure but I saw io.digdag.core.crypto.SecretCryptoProvider Is it secret related?
No, I didn't set the key.

result on debian8 :ok:
`secret encryption engine: disabled` is printed.

```
vagrant@debian:~/docker-recipes/digdag-embulk$ digdag scheduler
2017-06-23 21:08:26 +0200: Digdag v0.9.12
2017-06-23 21:08:28 +0200 [INFO] (main): secret encryption engine: disabled
2017-06-23 21:08:28 +0200 [INFO] (main): Added new revision 1
2017-06-23 21:08:28 +0200 [INFO] (main): XNIO version 3.3.6.Final
2017-06-23 21:08:28 +0200 [INFO] (main): XNIO NIO Implementation Version 3.3.6.Final
2017-06-23 21:08:28 +0200 [INFO] (main): Starting server on 127.0.0.1:65432
2017-06-23 21:08:28 +0200 [INFO] (main): Bound on 127.0.0.1:65432 (api)
2017-06-23 21:09:00 +0200 [INFO] (scheduler-0): Starting a new session project id=1 workflow name=mydag session_time=2017-06-24T04:09:00+09:00
2017-06-23 21:09:03 +0200 [INFO] (0024@[0:default]+mydag+task): embulk>: config.yml
2017-06-23 21:09:09.392 +0200: Embulk v0.8.21
2017-06-23 21:09:12.447 +0200 [INFO] (0001:transaction): Listing local files at directory '.' filtering filename by prefix 'test.csv'
2017-06-23 21:09:12.449 +0200 [INFO] (0001:transaction): "follow_symlinks" is set false. Note that symbolic links to directories are skipped.
2017-06-23 21:09:12.450 +0200 [INFO] (0001:transaction): Loading files [test.csv]
2017-06-23 21:09:12.569 +0200 [INFO] (0001:transaction): Using local thread executor with max_threads=2 / tasks=1
2017-06-23 21:09:12.588 +0200 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2017-06-23 21:09:12.894 +0200 [WARN] (0014:task-0000): Skipped line 2 (java.lang.NumberFormatException: For input string: "# comment line"): # comment line
2017-06-23 21:09:12.899 +0200 [WARN] (0014:task-0000): Skipped line 5 (Too many columns): 1005, "foo,bar\.piyo",,
2017-06-23 21:09:12.899 +0200 [WARN] (0014:task-0000): Skipped line 6 (java.lang.NumberFormatException: For input string: "## coment line"): ## coment line
2017-06-23 21:09:12.899 +0200 [WARN] (0014:task-0000): Skipped line 7 (Too many columns): 444444444, ""12345"", """123,45""", 12345
1004, hoge, 12ffe, 2554
1006, fuga1, fgr@7-, -46uaf
2017-06-23 21:09:12.900 +0200 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2017-06-23 21:09:12.903 +0200 [INFO] (main): Committed.
2017-06-23 21:09:12.903 +0200 [INFO] (main): Next config diff: {"in":{"last_path":"test.csv"},"out":{}}
```

**Comment by hiroyuki-sato** [comment]
@koooge Thank you for your comment. I'll check it. please wait a while.

**Comment by frsyuki** [comment]
`digdag run` command lists files on the current directory and it traverses subdirectories recursively. When you run `digdag run` in docker container, probably it ran on `/`. `/proc` is a subdirectory of `/` and apparently it includes recursive symbolic link: `/proc/self/task/178/fd/24 -> /`. So listing up files recursively caused infinite loop.

You should be able to avoid this problem by using another working directory.

**Comment by gms-ta-koge** [comment]
Okay, it became to work correctly. Thank you.

**Comment by koooge** [comment]
Okay, it became to work correctly. Thank you.
