### ISSUE TITLE
Emr operator throws error on executing steps using non-us region for s3 staging directory.

### ISSUE THREAD

**Issue by krt** [treasure-data/digdag#632]
I've tried to use emr operator with EMR, S3 on Tokyo region, but failed on executing simple steps.

stderr looks like this:

```
Traceback (most recent call last):
  File "/mnt/var/lib/hadoop/steps/s-xxx/./runner.py", line 134, in <module>
    status = main()
  File "/mnt/var/lib/hadoop/steps/s-xxx/./runner.py", line 105, in main
    download_to_filename(s3, args.config_uri, config_filename)
  File "/mnt/var/lib/hadoop/steps/s-xxx/./runner.py", line 38, in download_to_filename
    download_to_file(s3, src, f)
  File "/mnt/var/lib/hadoop/steps/s-xxx/./runner.py", line 28, in download_to_file
    key.get_contents_to_file(f)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 1650, in get_contents_to_file
    response_headers=response_headers)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 1482, in get_file
    query_args=None)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 1514, in _get_file_internal
    override_num_retries=override_num_retries)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 343, in open
    override_num_retries=override_num_retries)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 303, in open_read
    self.resp.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'ap-northeast-1'</Message><Region>ap-northeast-1</Region><RequestId>xxx</RequestId><HostId>xxx</HostId></Error>
Command exiting with ret '1'
```

Temporary this error was fixed since I've compiled digdag-cli with dirty hack on `runner.py`, fixed hard-coded variable `host` with "s3-ap-northeast-1.amazonaws.com".
https://github.com/treasure-data/digdag/blob/master/digdag-standards/src/main/resources/io/digdag/standards/operator/aws/runner.py#L101

I’m just wondering if the variable `host` should use secret value for 'aws.s3.region' or 'aws.region'.
Any comments or suggestions are welcome.

**Comment by komamitsu** [comment]
Sorry for our late reply and thank you for the reporting. We'll look into this issue later.

**Comment by 1ambda** [comment]
Have the same issue, I did set all of secrets regard to regions and endpoints.

```
$ digdag secrets --project test

2018-12-07 17:37:36 +0900: Digdag v0.9.31

aws.access_key_id
aws.secret_access_key
aws.emr.endpoint
aws.s3.endpoint
aws.emr.region
aws.s3.region
aws.region
```

with this workflow, but failed.

```yaml
+run:
  emr>:
  action_on_failure: CONTINUE
  cluster: ${emr_cluster.id}
  staging: ${emr_cluster.digdag_staging_dir}

  steps:
  - type: command
    command: echo
    args: [hello, world]
```

Here is a step error in AWS EMR (steps -> log files -> controller)

```
2018-12-07T08:39:16.108Z INFO Ensure step 19 jar file s3://us-east-1.elasticmapreduce/libs/script-runner/script-runner.jar
INFO Failed to download: s3://us-east-1.elasticmapreduce/libs/script-runner/script-runner.jar
java.lang.RuntimeException: Error whilst fetching 's3://us-east-1.elasticmapreduce/libs/script-runner/script-runner.jar'
	at aws157.instancecontroller.util.S3Wrapper.fetchS3HadoopFileToLocal(S3Wrapper.java:412)
	at aws157.instancecontroller.util.S3Wrapper.fetchHadoopFileToLocal(S3Wrapper.java:351)
	at aws157.instancecontroller.master.steprunner.HadoopJarStepRunner$Runner.<init>(HadoopJarStepRunner.java:243)
	at aws157.instancecontroller.master.steprunner.HadoopJarStepRunner.createRunner(HadoopJarStepRunner.java:152)
	at aws157.instancecontroller.master.steprunner.HadoopJarStepRunner.createRunner(HadoopJarStepRunner.java:146)
	at aws157.instancecontroller.master.steprunner.StepExecutor.runStep(StepExecutor.java:136)
	at aws157.instancecontroller.master.steprunner.StepExecutor.run(StepExecutor.java:70)
	at aws157.instancecontroller.master.steprunner.StepExecutionManager.enqueueStep(StepExecutionManager.java:246)
	at aws157.instancecontroller.master.steprunner.StepExecutionManager.doRun(StepExecutionManager.java:193)
	at aws157.instancecontroller.master.steprunner.StepExecutionManager.access$000(StepExecutionManager.java:33)
	at aws157.instancecontroller.master.steprunner.StepExecutionManager$1.run(StepExecutionManager.java:94)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect;
```

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
