### ISSUE TITLE
scheduler ResourceConflictException

### ISSUE THREAD

**Issue by wigbam** [treasure-data/digdag#711]
Hi,

Trying to run scheduler as follows:
`digdag scheduler -o .digdag/db/digdag. -O .digdag/log`

works fine the first time. On subsequent executions I get the following exception:

`Exception in thread "main" java.lang.Error: java.lang.reflect.InvocationTargetException
	at org.embulk.guice.LifeCycleModule$1$1.afterInjection(LifeCycleModule.java:81)
	at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:115)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at org.embulk.guice.Bootstrap.start(Bootstrap.java:155)
	at org.embulk.guice.Bootstrap.build(Bootstrap.java:117)
	at org.embulk.guice.Bootstrap.initializeCloseable(Bootstrap.java:112)
	at io.digdag.guice.rs.server.undertow.UndertowBootstrap.initialize(UndertowBootstrap.java:70)
	at io.digdag.guice.rs.GuiceRsServletContainerInitializer.processBootstrap(GuiceRsServletContainerInitializer.java:61)
	at io.digdag.guice.rs.GuiceRsServletContainerInitializer.onStartup(GuiceRsServletContainerInitializer.java:36)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:186)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:171)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:234)
	at io.digdag.guice.rs.server.undertow.UndertowServer.start(UndertowServer.java:179)
	at io.digdag.server.ServerBootstrap.start(ServerBootstrap.java:73)
	at io.digdag.cli.Sched.startScheduler(Sched.java:108)
	at io.digdag.cli.Sched.main(Sched.java:55)
	at io.digdag.cli.Main.cli(Main.java:187)
	at io.digdag.cli.Main.main(Main.java:82)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.embulk.guice.LifeCycleManager.startInstance(LifeCycleManager.java:203)
	at org.embulk.guice.LifeCycleManager.addInstance(LifeCycleManager.java:185)
	at org.embulk.guice.LifeCycleModule$1$1.afterInjection(LifeCycleModule.java:78)
	... 33 more
Caused by: java.lang.RuntimeException: io.digdag.core.repository.ResourceConflictException: Resource already exists: revision=1 in project id=1
	at io.digdag.cli.Sched$RevisionAutoReloaderStarter.start(Sched.java:158)
	... 40 more
Caused by: io.digdag.core.repository.ResourceConflictException: Resource already exists: revision=1 in project id=1
	at io.digdag.core.database.BasicDatabaseStoreManager.catchConflict(BasicDatabaseStoreManager.java:78)
	at io.digdag.core.database.DatabaseProjectStoreManager$DatabaseProjectControlStore.insertRevision(DatabaseProjectStoreManager.java:385)
	at io.digdag.core.repository.ProjectControl.insertRevision(ProjectControl.java:56)
	at io.digdag.core.LocalSite.lambda$storeLocalWorkflowsImpl$1(LocalSite.java:102)
	at io.digdag.core.database.DatabaseProjectStoreManager$DatabaseProjectStore.lambda$putAndLockProject$4(DatabaseProjectStoreManager.java:199)
	at io.digdag.core.database.BasicDatabaseStoreManager.transaction(BasicDatabaseStoreManager.java:192)
	at io.digdag.core.database.BasicDatabaseStoreManager.transaction(BasicDatabaseStoreManager.java:171)
	at io.digdag.core.database.DatabaseProjectStoreManager$DatabaseProjectStore.putAndLockProject(DatabaseProjectStoreManager.java:179)
	at io.digdag.core.LocalSite.storeLocalWorkflowsImpl(LocalSite.java:98)
	at io.digdag.core.LocalSite.storeLocalWorkflows(LocalSite.java:136)
	at io.digdag.cli.RevisionAutoReloader$ReloadTarget.storeProject(RevisionAutoReloader.java:134)
	at io.digdag.cli.RevisionAutoReloader$ReloadTarget.<init>(RevisionAutoReloader.java:123)
	at io.digdag.cli.RevisionAutoReloader$ReloadTarget.<init>(RevisionAutoReloader.java:111)
	at io.digdag.cli.RevisionAutoReloader.lambda$watch$0(RevisionAutoReloader.java:73)
	at io.digdag.core.database.ThreadLocalTransactionManager.begin(ThreadLocalTransactionManager.java:250)
	at io.digdag.core.database.ThreadLocalTransactionManager.begin(ThreadLocalTransactionManager.java:235)
	at io.digdag.cli.RevisionAutoReloader.watch(RevisionAutoReloader.java:72)
	at io.digdag.cli.Sched$RevisionAutoReloaderStarter.start(Sched.java:155)
	... 40 more
`

**Comment by hiroyuki-sato** [comment]
Hello, @wigbam 

Thank you for reporting this issue.

Do you want to run scheduled task? If so, I recommend you to execute `digdag server` command instead scheduler The `scheduler` does not test well.

I reproduced your issue in my environment with the following dig file.
digdag 0.9.21

```yaml
schedule:digdag scheduler -o .digdag/db/digdag -O .digdag/logschedule
  minutes_interval>: 1

+setup:
  sh>: echo start ${session_time}
```

And execute `digdag scheduler -o .digdag/db/digdag -O .digdag/logs` twice.

It seems that you have to execute `rm -f .digdag/db/digdag/*` before launch `digdag scheduler`

**Comment by muga** [comment]
This is expected behavior but we'd better to improve validation or error message to avoid any confusing. I will keep opening this ticket to do that.
