### ISSUE TITLE
PgJDBC 42.2.0 Will fix #583

### ISSUE THREAD

**Issue by hiroyuki-sato** [treasure-data/digdag#715]
PgJDBC 42.2.0 has been released.

It support get/setNetworkTimeout() in connections feature.

This feature will fix #583. 

https://github.com/pgjdbc/pgjdbc/blob/master/CHANGELOG.md#added

**Comment by hiroyuki-sato** [comment]
PgJDBC driver claim with the following message after update PgJDBC driver to 4.2.20.
It may need to change default connection pool size.

https://github.com/treasure-data/digdag/blob/823b35373cad913b0d5d617b164be7679bfc35ba/digdag-core/src/main/java/io/digdag/core/database/DatabaseConfig.java#L95-L96

brettwooldridge who is HikcariCP maintainer commented about this a few months ago.
https://github.com/treasure-data/digdag/issues/478#issuecomment-338361719

```
org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:131)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:452)
	at org.postgresql.Driver.access$100(Driver.java:61)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:362)
	at java.lang.Thread.run(Thread.java:745)
```

```diff
diff --git a/digdag-core/build.gradle b/digdag-core/build.gradle
index f10ecf397..e4ac44f6e 100644
--- a/digdag-core/build.gradle
+++ b/digdag-core/build.gradle
@@ -13,9 +13,9 @@ dependencies {
     compile "com.fasterxml.jackson.module:jackson-module-guice:${project.ext.jacksonVersion}"
     compile "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:${project.ext.jacksonVersion}"
     compile 'org.jdbi:jdbi:2.75'
-    compile 'com.zaxxer:HikariCP:2.4.7'
+    compile 'com.zaxxer:HikariCP:2.7.1'
     compile 'com.h2database:h2:1.4.192'
-    compile 'org.postgresql:postgresql:9.4.1211'
+    compile 'org.postgresql:postgresql:42.2.2'
     compile 'org.yaml:snakeyaml:1.17'
     compile 'com.google.code.findbugs:annotations:3.0.1'
     compile 'org.weakref:jmxutils:1.19'
diff --git a/digdag-standards/build.gradle b/digdag-standards/build.gradle
index 913ede035..4019c6146 100644
--- a/digdag-standards/build.gradle
+++ b/digdag-standards/build.gradle
@@ -20,7 +20,7 @@ dependencies {
     compile 'org.yaml:snakeyaml:1.17'
 
     // postgresql
-    compile 'org.postgresql:postgresql:9.4.1211'
+    compile 'org.postgresql:postgresql:42.2.2'
 
     // aws
     compile "com.amazonaws:aws-java-sdk-kms:${project.ext.awsJavaSdkVersion}"
```
