### ISSUE TITLE
Retry operation behaves unexpectedly when combined with a sh:> operator

### ISSUE THREAD

**Issue by aoetk** [treasure-data/digdag#728]
## Abstract

Retry operation behaves unexpectedly when combined with a sh:> operator.

### Expected behavior

If the retried task succeeds, the task group is recorded as succeeded and the subsequent task is executed.

### Actual behavior

Even if the retried task succeeds, the specified number of retries are executed, and the task group is recorded as failed. The subsequent task isn't executed.

### Version

0.9.24

## Reproduce example

Create a shell script like the following.
The first execution of the script fails and the subsequent execution succeeds. The first execution of the script fails and the subsequent execution succeeds.

```shell
#!/usr/bin/env bash

if [ -e /tmp/executed ]; then
    echo "Success."
else
    echo "Failed." > /tmp/executed
    exit 1
fi
```

Create a workflow that uses the shell script.

```yaml
timezone: Asia/Tokyo

_error:
  echo>: Workflow failed.

+retrytask:
  _retry: 5

  +run:
    sh>: ~/test.sh

+teardown:
  echo>: Workflow succeeded.
```

The result of the workflow is as follows.

```
$ digdag run --session 2018-01-31 testflow
2018-02-02 19:21:44 +0900: Digdag v0.9.24
2018-02-02 19:21:45 +0900 [INFO] (main): Using session /home/foo/mydag/.digdag/status/20180131T000000+0900.
2018-02-02 19:21:45 +0900 [INFO] (main): Starting a new session project id=1 workflow name=testflow session_time=2018-01-31T00:00:00+09:00
2018-02-02 19:21:46 +0900 [INFO] (0017@[0:default]+testflow+retrytask+run): sh>: ~/test.sh
2018-02-02 19:21:46 +0900 [ERROR] (0017@[0:default]+testflow+retrytask+run): Task failed with unexpected error: Command failed with code 1
java.lang.RuntimeException: Command failed with code 1
	at io.digdag.standards.operator.ShOperatorFactory$ShOperator.runTask(ShOperatorFactory.java:143)
	at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
	at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:312)
	at io.digdag.cli.Run$OperatorManagerWithSkip.callExecutor(Run.java:694)
	at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:254)
	at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137)
	at io.digdag.core.agent.LocalWorkspaceManager.withExtractedArchive(LocalWorkspaceManager.java:25)
	at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135)
	at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119)
	at io.digdag.cli.Run$OperatorManagerWithSkip.run(Run.java:676)
	at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2018-02-02 19:21:47 +0900 [INFO] (0017@[0:default]+testflow+retrytask+run): sh>: ~/test.sh
Success.
2018-02-02 19:21:47 +0900 [INFO] (0017@[0:default]+testflow+retrytask+run): sh>: ~/test.sh
Success.
2018-02-02 19:21:48 +0900 [WARN] (0017@[0:default]+testflow+retrytask+run): Skipped
2018-02-02 19:21:48 +0900 [WARN] (0017@[0:default]+testflow+retrytask+run): Skipped
2018-02-02 19:21:48 +0900 [WARN] (0017@[0:default]+testflow+retrytask+run): Skipped
2018-02-02 19:21:48 +0900 [INFO] (0017@[0:default]+testflow^failure-alert): type: notify
2018-02-02 19:21:48 +0900 [INFO] (0021@[0:default]+testflow^error): echo>: Workflow failed.
Workflow failed.
error: 
  * +testflow+retrytask+run:
    Command failed with code 1 (runtime)

Task state is saved at /home/foo/mydag/.digdag/status/20180131T000000+0900 directory.
  * Use --session <daily | hourly | "yyyy-MM-dd[ HH:mm:ss]"> to not reuse the last session time.
  * Use --rerun, --start +NAME, or --goal +NAME argument to rerun skipped tasks.
```

**Comment by hiroyuki-sato** [comment]
Hello, @aoetk. latest digdag(>= v0.9.27) may fix this issue. Could you try it?

**Comment by aoetk** [comment]
Sorry for the late reply. I confirmed that the problem was solved. Thank you.
