### ISSUE TITLE
A task is never finished when "File name too long" by log file occurs

### ISSUE THREAD

**Issue by toru-takahashi** [treasure-data/digdag#729]
## Environment
digdag 0.9.24 (Server mode)

## Problem
When a digfile is pushed, the following validation works well.

```
Failed to store: {"message":"Validating project failed\nworkflow /tmp/digdag-tempdir5894056088905123786/push/new-project_1377544233838658341/new.dig Validating workflow failed\ntask name must not be longer than 255 characters: \"
```

On the other hands, the following dig file doesn't be validated. When this dig file run, the following error occurs and the task keeps to show "running" status.

```
+repeat:
  loop>: 10
  _do:
    +no_problem:
      sh>: echo "hello world"
    +aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_aaa:
      if>: ${i != 0}
      _do:
        sh>: echo "${i}"
```

```
[root@ip-172-31-46-53 logs]# tail server.log
Caused by: java.nio.file.FileSystemException: /opt/digdag/logs/tasklogs/2018-02-05/0.1new@20180205T072606+0000/+new+repeat^sub+loop-0+aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@5a78070f37baf7c0.3079@ip-172-31-46-53.ec2.internal.log.gz: File name too long
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at io.digdag.core.log.LocalFileLogServerFactory$LocalFileLogServer$LocalFileDirectTaskLogger.<init>(LocalFileLogServerFactory.java:170)
	at io.digdag.core.log.LocalFileLogServerFactory$LocalFileLogServer.newDirectTaskLogger(LocalFileLogServerFactory.java:147)
	... 9 common frames omitted
```

## Expected Results
Adding validation for a length of task name.
Or
Workflow should be failed immediately when this error happens.

**Comment by mjtice** [comment]
Same issue for me.  Took me a while to track it down (I didn't think of looking at the digdag log...).

I've got some tasks get are generating really long filenames:  e.g.
```
/mnt/apps/logs/dbaapps01.prod.fooz.com/digdag/sessions/2018-03-12/0.1refresh_scrub_databases@20180312T073750-0600/+refresh_scrub_databases+refresh_scrubbers^sub+for-0=my_class=0=prt+process_scrubbers+postmake_prt^sub+mask_scrub_prt+create_camo_validator_premask+validate_camouflage_masking^sub+for-0=project=0=SAPI.AS2@5aa6987f21426780.12725@dbaapps01.prod.fooz.com.log.gz
```

Which is throwing this message

```
2018-03-12 09:10:55 -0600 [ERROR] (task-thread-5) io.digdag.core.agent.MultiThreadAgent: Uncaught exception. Task queue will detect this failure and this task will be retried later.
java.lang.RuntimeException: java.nio.file.FileSystemException: /mnt/apps/logs/dbaapps01.prod.fooz.com/digdag/sessions/2018-03-12/0.1refresh_scrub_databases@20180312T073750-0600/+refresh_scrub_databases+refresh_scrubbers^sub+for-0=my_class=0=prt+process_scrubbers+postmake_prt^sub+mask_scrub_prt+create_camo_validator_premask+validate_camouflage_masking^sub+for-0=project=0=SAPI.AS2@5aa6987f21426780.12725@dbaapps01.prod.fooz.com.log.gz: File name too long
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at io.digdag.core.log.LocalFileLogServerFactory$LocalFileLogServer.newDirectTaskLogger(LocalFileLogServerFactory.java:150)
	at io.digdag.core.log.LogServerManager.newInProcessTaskLogger(LogServerManager.java:78)
	at io.digdag.core.agent.InProcessTaskCallbackApi.newTaskLogger(InProcessTaskCallbackApi.java:92)
	at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:114)
	at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by muga** [comment]
The error could be reproduced with local log-server. When we use S3 log-server, log files are not created on specified S3 path with any error messages.

**Comment by hiroyuki-sato** [comment]
@muga @toru-takahashi v0.9.26 fixed this issue. please take a look when you have time.
