### ISSUE TITLE
java.lang.RuntimeException: Command failed with code 1

### ISSUE THREAD

**Issue by 1046744978** [treasure-data/digdag#739]
Task failed with unexpected error: Command failed with code 1
java.lang.RuntimeException: Command failed with code 1
        at io.digdag.standards.operator.ShOperatorFactory$ShOperator.runTask(ShOperatorFactory.java:143)
        at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
        at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:312)
        at io.digdag.cli.Run$OperatorManagerWithSkip.callExecutor(Run.java:694)
        at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:254)
        at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137)
        at io.digdag.core.agent.LocalWorkspaceManager.withExtractedArchive(LocalWorkspaceManager.java:25)
        at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135)
        at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119)
        at io.digdag.cli.Run$OperatorManagerWithSkip.run(Run.java:676)
        at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by hiroyuki-sato** [comment]
Hello, @1046744978 

Could you tell me more detail about your problem?
(Digdag version, example dig file and so on).

It seems normal behavior.
Digdag expects exit status 0 if task succeeds.

If `sh` operator exit with status 1, those errors will report. 
Here is the reproduce code I think.

```yaml
timezone: UTC
+test:
  sh>: exit 1
```


```
digdag run hoge
2018-03-21 21:38:58 +0900: Digdag v0.9.24
2018-03-21 21:39:00 +0900 [WARN] (main): Using a new session time 2018-03-21T00:00:00+00:00.
2018-03-21 21:39:00 +0900 [INFO] (main): Using session /private/tmp/hoge/.digdag/status/20180321T000000+0000.
2018-03-21 21:39:00 +0900 [INFO] (main): Starting a new session project id=1 workflow name=hoge session_time=2018-03-21T00:00:00+00:00
2018-03-21 21:39:01 +0900 [INFO] (0017@[0:default]+hoge+test): sh>: exit 1
2018-03-21 21:39:01 +0900 [ERROR] (0017@[0:default]+hoge+test): Task failed with unexpected error: Command failed with code 1
java.lang.RuntimeException: Command failed with code 1
	at io.digdag.standards.operator.ShOperatorFactory$ShOperator.runTask(ShOperatorFactory.java:143)
	at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
	at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:312)
	at io.digdag.cli.Run$OperatorManagerWithSkip.callExecutor(Run.java:694)
	at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:254)
	at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137)
	at io.digdag.core.agent.LocalWorkspaceManager.withExtractedArchive(LocalWorkspaceManager.java:25)
	at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135)
	at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119)
	at io.digdag.cli.Run$OperatorManagerWithSkip.run(Run.java:676)
	at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-03-21 21:39:01 +0900 [INFO] (0017@[0:default]+hoge^failure-alert): type: notify
error:
  * +hoge+test:
    Command failed with code 1 (runtime)

Task state is saved at /private/tmp/hoge/.digdag/status/20180321T000000+0000 directory.
  * Use --session <daily | hourly | "yyyy-MM-dd[ HH:mm:ss]"> to not reuse the last session time.
  * Use --rerun, --start +NAME, or --goal +NAME argument to
```

**Comment by muga** [comment]
@1046744978 As @hiroyuki-sato commented above, `sh` operator checks if exit code is zero or not and throws `RuntimeException` expectedly if non-zero. The behavior is same as `py` and `rb` operators'. I will close this ticket but, please let us know if you still think that the `sh` operator doesn't work unexpectedly.
