### ISSUE TITLE
[Q] Can't push because of proxy

### ISSUE THREAD

**Issue by chaspy** [treasure-data/digdag#745]
I pushed to digdag server, but response was 302.

Client and server are the same machine.

I set my own IP address to the environment variable no_proxy, but it seems to be connected to proxy.

Can I not connect to proxy?

## log

```
# digdag push sample -l trace
2018-03-30 10:51:27 +0900: Digdag v0.9.24
2018-03-30 10:51:27 +0900 [DEBUG] (main) org.eclipse.aether.internal.impl.DefaultLocalRepositoryProvider: Using manager EnhancedLocalRepositoryManager with priority 10.0 for .digdag/plugins
2018-03-30 10:51:27 +0900 [DEBUG] (main) io.digdag.core.database.DataSourceProvider: Using database URL jdbc:h2:mem:digdag-e0c8b22a-bdf4-4f76-beff-5b134c1f557a
Creating .digdag/tmp/archive-1774246346957958938.tar.gz...
  Archiving sample.dig
Workflows:
  sample.dig
2018-03-30 10:51:28 +0900 [DEBUG] (main) org.eclipse.aether.internal.impl.DefaultLocalRepositoryProvider: Using manager EnhancedLocalRepositoryManager with priority 10.0 for /root/.config/digdag/plugins
2018-03-30 10:51:28 +0900 [DEBUG] (main) io.digdag.cli.client.ClientCommand: Using endpoint http://127.0.0.1:65432
2018-03-30 10:51:28 +0900 [WARN] (main): HTTP proxy authentication not supported. Ignoring proxy username and password.
2018-03-30 10:51:28 +0900 [DEBUG] (main) org.jboss.logging.LoggerProviders: Logging Provider: org.jboss.logging.Slf4jLoggerProvider
2018-03-30 10:51:28 +0900 [DEBUG] (main) org.jboss.resteasy.plugins.providers.DocumentProvider: RESTEASY002330: Unable to retrieve config: expandEntityReferences defaults to false
2018-03-30 10:51:28 +0900 [DEBUG] (main) org.jboss.resteasy.plugins.providers.DocumentProvider: RESTEASY002335: Unable to retrieve config: enableSecureProcessingFeature defaults to true
2018-03-30 10:51:28 +0900 [DEBUG] (main) org.jboss.resteasy.plugins.providers.DocumentProvider: RESTEASY002325: Unable to retrieve config: disableDTDs defaults to true
2018-03-30 10:51:28 +0900 [DEBUG] (main) org.jboss.resteasy.plugins.providers.DocumentProvider: RESTEASY002330: Unable to retrieve config: expandEntityReferences defaults to false
2018-03-30 10:51:28 +0900 [DEBUG] (main) org.jboss.resteasy.plugins.providers.DocumentProvider: RESTEASY002335: Unable to retrieve config: enableSecureProcessingFeature defaults to true
2018-03-30 10:51:28 +0900 [DEBUG] (main) org.jboss.resteasy.plugins.providers.DocumentProvider: RESTEASY002325: Unable to retrieve config: disableDTDs defaults to true
2018-03-30 10:51:29 +0900 [DEBUG] (main) org.apache.http.impl.conn.BasicClientConnectionManager: Get connection for route {}->http://proxy.XXX.com:8080->http://127.0.0.1:65432
2018-03-30 10:51:29 +0900 [DEBUG] (main) org.apache.http.impl.conn.DefaultClientConnectionOperator: Connecting to rep.proxy.nic.fujitsu.com:8080
2018-03-30 10:51:29 +0900 [DEBUG] (main) org.apache.http.client.protocol.RequestAddCookies: CookieSpec selected: default
2018-03-30 10:51:29 +0900 [DEBUG] (main) org.apache.http.client.protocol.RequestAuthCache: Auth cache not set in the context
2018-03-30 10:51:29 +0900 [DEBUG] (main) org.apache.http.client.protocol.RequestTargetAuthentication: Target auth state: UNCHALLENGED
2018-03-30 10:51:29 +0900 [DEBUG] (main) org.apache.http.client.protocol.RequestProxyAuthentication: Proxy auth state: UNCHALLENGED
2018-03-30 10:51:29 +0900 [DEBUG] (main) org.apache.http.impl.client.DefaultRequestDirector: Attempt 1 to execute request
2018-03-30 10:51:29 +0900 [DEBUG] (main) org.apache.http.impl.conn.DefaultClientConnection: Sending request: GET http://127.0.0.1:65432/api/version/check?client=0.9.24 HTTP/1.1
2018-03-30 10:51:29 +0900 [DEBUG] (main) org.apache.http.impl.conn.DefaultClientConnection: Receiving response: HTTP/1.1 302 Found
2018-03-30 10:51:29 +0900 [DEBUG] (main) org.apache.http.impl.conn.BasicClientConnectionManager: Releasing connection org.apache.http.impl.conn.ManagedClientConnectionImpl@62b3df3a
2018-03-30 10:51:29 +0900 [DEBUG] (main) org.apache.http.impl.conn.DefaultClientConnection: Connection 0.0.0.0:43096<->10.X.XX.XX:8080 shut down
error: HTTP 302 Found (web application)
javax.ws.rs.WebApplicationException: HTTP 302 Found
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:220)
        at io.digdag.client.DigdagClient.lambda$invokeWithRetry$3(DigdagClient.java:682)
        at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
        at com.github.rholder.retry.Retryer.call(Retryer.java:160)
        at io.digdag.client.DigdagClient.invokeWithRetry(DigdagClient.java:678)
        at io.digdag.client.DigdagClient.doGet(DigdagClient.java:894)
        at io.digdag.client.DigdagClient.checkClientVersion(DigdagClient.java:825)
        at io.digdag.cli.client.ClientCommand.buildClient(ClientCommand.java:115)
        at io.digdag.cli.client.ClientCommand.buildClient(ClientCommand.java:94)
        at io.digdag.cli.client.Push.push(Push.java:119)
        at io.digdag.cli.client.Push.mainWithClientException(Push.java:53)
        at io.digdag.cli.client.ClientCommand.main(ClientCommand.java:64)
        at io.digdag.cli.Main.cli(Main.java:187)
        at io.digdag.cli.Main.main(Main.java:82)
```

Environment variable

```
# echo $no_proxy
localhost,127.0.0.1,${my_ip}
```

**Comment by hiroyuki-sato** [comment]
Hello, @chaspy 

Digdag **doesn't** support `no_proxy` parameter yet. 

Alternative idea.
How about `env http_proxy=XXX digdag push`.. when you use Proxy? 

ref: [Twitter](https://twitter.com/nora96o/status/958255020838825984) written in Japanese.

**Comment by chaspy** [comment]
Hi, @hiroyuki-sato 

It is necessary to always connect to the proxy because our digdag is in the company... so I'm glad that digdag will support no_proxy.

I created an alias to clear the environment variable as workaround.

.bashrc
```bash
function _digdag() {
  env -i bash -c "digdag $1 $2"
}

alias digdag="_digdag"
```

Thanx!
