### ISSUE TITLE
Can't use ENTRYPOINT of docker?

### ISSUE THREAD

**Issue by grezar** [treasure-data/digdag#776]
Hi.
I got following error when I run workflow with docker container(using ENTRYPOINT).
Here is my workflow and container definition -> https://gist.github.com/grezar/131f6c5dbf063ae2c6435b3b53fdd085

```
2018-05-08 21:57:00.494 +0900 [INFO] (0311@[0:test]+my_workflow+check) io.digdag.core.agent.OperatorManager: rb>: Task::MyWorkflow.greeting
2018-05-08 21:57:00.497 +0900 [INFO] (0311@[0:test]+my_workflow+check) io.digdag.standards.command.DockerCommandExecutor: Pulling docker image grezar/digdag-ruby
this is entrypoint.sh
2018-05-08 21:57:01.986 +0900 [ERROR] (0311@[0:test]+my_workflow+check) io.digdag.core.agent.OperatorManager: Task failed with unexpected error: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: /tmp/digdag-tempdir6198439649984576529/workspace/+my_workflow+check_2539744499074107632/.digdag/tmp/digdag-rb-out-1475238349827292872.tmp; line: 1, column: 1]
java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: /tmp/digdag-tempdir6198439649984576529/workspace/+my_workflow+check_2539744499074107632/.digdag/tmp/digdag-rb-out-1475238349827292872.tmp; line: 1, column: 1]
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at io.digdag.standards.operator.RbOperatorFactory$RbOperator.runTask(RbOperatorFactory.java:95)
	at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
	at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:312)
	at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:254)
	at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137)
	at io.digdag.core.agent.ExtractArchiveWorkspaceManager.withExtractedArchive(ExtractArchiveWorkspaceManager.java:77)
	at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135)
	at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119)
	at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: /tmp/digdag-tempdir6198439649984576529/workspace/+my_workflow+check_2539744499074107632/.digdag/tmp/digdag-rb-out-1475238349827292872.tmp; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3781)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3721)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2620)
	at io.digdag.standards.operator.RbOperatorFactory$RbOperator.runCode(RbOperatorFactory.java:163)
	at io.digdag.standards.operator.RbOperatorFactory$RbOperator.runTask(RbOperatorFactory.java:92)
	... 13 common frames omitted
2018-05-08 21:57:03.143 +0900 [INFO] (0785@[0:test]+my_workflow^failure-alert) io.digdag.core.agent.OperatorManager: type: notify
```

This error has occurred since trying to run entrypoint.sh. Although it looks entrypoint.sh runs successfly, rb operator's execution is failed.
Is this a bug? 
Please say if you need more information.

**Comment by muga** [comment]
Currently `rb>` operator doesn't support `ENTRYPOINT`. It overrides what is executed with runner script, which is provided by Digdag. This error happens when the runner script cannot be executed and write a task result file appropriately. If you have any good ideas to support `ENTRYPOINT`, please let us know.

**Comment by yoyama** [comment]
Close because no more activity.
