### ISSUE TITLE
failure-alert task is skipped when failure retry fails

### ISSUE THREAD

**Issue by keijsuzu** [treasure-data/digdag#825]
failure-alert task is skipped when failure retry fails.

I want you to execute it even when the retry fails.

and _error task too.

**Comment by hiroyuki-sato** [comment]
Hello, @keijsuzu 

Could you tell me more detail about your requirements?
Could you show me an example dig file?

Some issues fixed during v0.9.25 ~ v0.9.27 (0.9.27 not yet released now) about retry.
What digdag version are you use?

**Comment by keijsuzu** [comment]
Hello, @hiroyuki-sato 

I want to notify when the task fails even if the retry at the time of fail fails.

Sample dig file and other files is here.

- notification.dig
  ```
  +task:
    sh>: exit 1
  ```
- digdag/config
  ```
  notification.type = shell
  notification.shell.command = touch /tmp/test
  ```

The version I am using is v0.9.27.

**Comment by hiroyuki-sato** [comment]
Hello, @keijsuzu 

Are you use local mode? And does this mean the following, right?.

* First `Digdag run` (first try) notify if the task fails.
* Second `Digdag run` (retry) doesn't notify even the task fails. (It skipped)
* You want to execute notify script if that task retry.

## 1. Detail

### 1.1 Script

digdag2.conf

```
notification.type = shell
notification.shell.command = touch /tmp/test
```

notification2.dig

```bash
+task:
  sh>: exit 1
```

### 1.2 First `digdag run`

```
digdag run -c digdag2.conf ./notification2.dig
2018-07-03 16:51:45 +0900: Digdag v0.9.27
2018-07-03 16:51:46 +0900 [WARN] (main): Using a new session time 2018-07-03T00:00:00+00:00.
2018-07-03 16:51:46 +0900 [INFO] (main): Using session /path/to/digdag-support/core_825_notify/.digdag/status/20180703T000000+0000.
2018-07-03 16:51:46 +0900 [INFO] (main): Starting a new session project id=1 workflow name=notification2 session_time=2018-07-03T00:00:00+00:00
2018-07-03 16:51:47 +0900 [INFO] (0017@[0:default]+notification2+task): sh>: exit 1
2018-07-03 16:51:47 +0900 [ERROR] (0017@[0:default]+notification2+task): Task failed with unexpected error: Command failed with code 1
java.lang.RuntimeException: Command failed with code 1
	at io.digdag.standards.operator.ShOperatorFactory$ShOperator.runTask(ShOperatorFactory.java:143)
	at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
	at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:312)
	at io.digdag.cli.Run$OperatorManagerWithSkip.callExecutor(Run.java:694)
	at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:254)
	at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137)
	at io.digdag.core.agent.LocalWorkspaceManager.withExtractedArchive(LocalWorkspaceManager.java:25)
	at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135)
	at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119)
	at io.digdag.cli.Run$OperatorManagerWithSkip.run(Run.java:676)
	at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-07-03 16:51:48 +0900 [INFO] (0017@[0:default]+notification2^failure-alert): type: notify # <-- notify
error:
  * +notification2+task:
    Command failed with code 1 (runtime)
```

### 1.3 Second `digdag run`


```
digdag run -c digdag2.conf ./notification2.dig
2018-07-03 16:52:06 +0900: Digdag v0.9.27
2018-07-03 16:52:07 +0900 [WARN] (main): Reusing the last session time 2018-07-03T00:00:00+00:00.
2018-07-03 16:52:07 +0900 [INFO] (main): Using session /path/to/digdag-support/core_825_notify/.digdag/status/20180703T000000+0000.
2018-07-03 16:52:08 +0900 [INFO] (main): Starting a new session project id=1 workflow name=notification2 session_time=2018-07-03T00:00:00+00:00
2018-07-03 16:52:09 +0900 [INFO] (0017@[0:default]+notification2+task): sh>: exit 1
2018-07-03 16:52:09 +0900 [ERROR] (0017@[0:default]+notification2+task): Task failed with unexpected error: Command failed with code 1
java.lang.RuntimeException: Command failed with code 1
	at io.digdag.standards.operator.ShOperatorFactory$ShOperator.runTask(ShOperatorFactory.java:143)
	at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
	at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:312)
	at io.digdag.cli.Run$OperatorManagerWithSkip.callExecutor(Run.java:694)
	at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:254)
	at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137)
	at io.digdag.core.agent.LocalWorkspaceManager.withExtractedArchive(LocalWorkspaceManager.java:25)
	at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135)
	at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119)
	at io.digdag.cli.Run$OperatorManagerWithSkip.run(Run.java:676)
	at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-07-03 16:52:09 +0900 [WARN] (0017@[0:default]+notification2^failure-alert): Skipped # <-- notify skipped.
error:
  * +notification2+task:
    Command failed with code 1 (runtime)
```

**Comment by keijsuzu** [comment]
Hello, @hiroyuki-sato 

> Are you use local mode?

My case is server mode.

> And does this mean the following, right?.

It is different from my case, but I want a notification even in that case.
My case is following.

- First Digdag run (first try) notify if the task fails.
```
$ digdag start test notification --session daily
```
- Digdag retry(resume mode).(It skipped)
```
$ digdag retry 1 --latest-revision --resume
```

**Comment by hiroyuki-sato** [comment]
Hello, @keijsuzu thank you for clarifying.

@muga Could you comment this issue?

* Digdag doesn't execute notification again when it notified once.
* server and local mode
* [reprodue code](https://github.com/treasure-data/digdag/issues/825#issuecomment-402050302)
* Digdag v0.9.27
