### ISSUE TITLE
Group retry does not work in call> operator

### ISSUE THREAD

**Issue by yoyama** [treasure-data/digdag#849]
Group retry does not work when the digdag script called from call> operator.

### Environment
Digdag version: 0.9.27
Mode: local

### Procedure for reproducing
* parent.dig
```
+call_child:
  call>: ./child.dig
```
* child.dig
```
_retry: 2
+run:
  sh>: sleep 3; exit 1
```
* Run
```
$ digdag  run --rerun ./parent.dig
```

* Result
Only executed one time, not retried.
```
2018-08-27 12:16:06 +0900: Digdag v0.9.27
2018-08-27 12:16:07 +0900 [WARN] (main): Reusing the last session time 2018-08-23T00:00:00+00:00.
2018-08-27 12:16:07 +0900 [INFO] (main): Using session /home/.../.digdag/status/20180823T000000+0000.
2018-08-27 12:16:07 +0900 [INFO] (main): Starting a new session project id=1 workflow name=parent session_time=2018-08-23T00:00:00+00:00
2018-08-27 12:16:08 +0900 [INFO] (0017@[0:default]+parent+call_child): call>: ./child.dig
2018-08-27 12:16:09 +0900 [INFO] (0017@[0:default]+parent+call_child^sub+run): sh>: sleep 3; exit 1
2018-08-27 12:16:12 +0900 [ERROR] (0017@[0:default]+parent+call_child^sub+run): Task failed with unexpected error: Command failed with code 1
java.lang.RuntimeException: Command failed with code 1
        at io.digdag.standards.operator.ShOperatorFactory$ShOperator.runTask(ShOperatorFactory.java:143)
        at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
        at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:312)
        at io.digdag.cli.Run$OperatorManagerWithSkip.callExecutor(Run.java:694)
        at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:254)
        at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137)
        at io.digdag.core.agent.LocalWorkspaceManager.withExtractedArchive(LocalWorkspaceManager.java:25)
        at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135)
        at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119)
        at io.digdag.cli.Run$OperatorManagerWithSkip.run(Run.java:676)
        at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2018-08-27 12:16:12 +0900 [INFO] (0017@[0:default]+parent^failure-alert): type: notify
error:
  * +parent+call_child^sub+run:
    Command failed with code 1 (runtime)

Task state is saved at /home/.../.digdag/status/20180823T000000+0000 directory.
  * Use --session <daily | hourly | "yyyy-MM-dd[ HH:mm:ss]"> to not reuse the last session time.
  * Use --rerun, --start +NAME, or --goal +NAME argument to rerun skipped tasks.
```

### Cause of problem
When added tasks to retry, INITIAL_TASK is not set to state_flags, so the tasks are not picked up in DatabaseSessionStoreManager.copyInitialTasksForRetry().
If I added INITIAL_TASK in TaskControl.addGeneratedSubtasks(), it looks like working correctly.
But I don't know the role of INITIAL_TASK, so it may not correct way.

**Comment by civitaspo** [comment]
This issue is produced when using `_retry` inside subtasks, not only `call>` operator. See the below condition.

* a.dig
  ```
  +exe:
    py>: x.y
  ```
* x.py
  ```
  import digdag
  
  def y():
      digdag.env.add_subtask({
          "_retry": 3,
          "_type": "fail",
          "_command": "failed...",
          })
  ```
* result: why `+subtask0` task is not retried?
  ```
  $ digdag run a.dig --no-save
  2018-12-12 17:16:19 +0900: Digdag v0.9.31
  2018-12-12 17:16:21 +0900 [WARN] (main): Reusing the last session time 2018-12-12T00:00:00+00:00.
  2018-12-12 17:16:21 +0900 [INFO] (main): Starting a new session project id=1 workflow name=a session_time=2018-12-12T00:00:00+00:00
  2018-12-12 17:16:23 +0900 [INFO] (0016@[0:default]+a+exe): py>: x.y
  2018-12-12 17:16:24 +0900 [INFO] (0016@[0:default]+a+exe^sub+subtask0): type: fail
  2018-12-12 17:16:24 +0900 [ERROR] (0016@[0:default]+a+exe^sub+subtask0): Task +a+exe^sub+subtask0 failed.
  failed...
  2018-12-12 17:16:24 +0900 [INFO] (0016@[0:default]+a^failure-alert): type: notify
  error:
    * +a+exe^sub+subtask0:
      failed...
  ```

This is a so critical issue for us because complicated workflows cannot be composed without subtasks( include `call>` operator). Please help...

**Comment by civitaspo** [comment]
thx!!
