### ISSUE TITLE
[issue] JsonParseException with digdag push >= 0.9.26

### ISSUE THREAD

**Issue by sonots-zozo** [treasure-data/digdag#947]
With digdag >= 0.9.26 and `Content-Encoding: gzip` server (such as with nginx), digdag push fails as:

```
error: com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: org.jboss.resteasy.client.jaxrs.internal.ClientResponse$InputStreamWrapper@6ad6fa53; line: 1, column: 2] (processing)
javax.ws.rs.ProcessingException: com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: org.jboss.resteasy.client.jaxrs.internal.ClientResponse$InputStreamWrapper@6ad6fa53; line: 1, column: 2]
        at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:300)
        at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readEntity(ClientResponse.java:196)
        at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:218)
        at io.digdag.client.DigdagClient.doGet(DigdagClient.java:896)
        at io.digdag.client.DigdagClient.checkClientVersion(DigdagClient.java:825)
        at io.digdag.cli.client.ClientCommand.buildClient(ClientCommand.java:115)
        at io.digdag.cli.client.ClientCommand.buildClient(ClientCommand.java:94)
        at io.digdag.cli.client.Push.push(Push.java:119)
        at io.digdag.cli.client.Push.mainWithClientException(Push.java:53)
        at io.digdag.cli.client.ClientCommand.main(ClientCommand.java:64)
        at io.digdag.cli.Main.cli(Main.java:187)
        at io.digdag.cli.Main.main(Main.java:82)
Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: org.jboss.resteasy.client.jaxrs.internal.ClientResponse$InputStreamWrapper@6ad6fa53; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._throwInvalidSpace(ParserMinimalBase.java:509)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2949)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:731)
        at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:774)
        at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:66)
        at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:56)
        at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:266)
```

I doubt that this bug is embedded by

* https://github.com/treasure-data/digdag/blob/7f7604d160b5de2ffab4809126d083eb49f39b47/digdag-client/src/main/java/io/digdag/client/DigdagClient.java#L219-L227
* and the upgrade of resteasy-client from 3.0.13.Final to 3.0.24.Final at [0.9.26](https://docs.digdag.io/releases/release-0.9.26.html)

**Comment by muga** [comment]
ah it should be bug. We will reproduce this issue first.

**Comment by sonots-zozo** [comment]
This bug occurs with resteasy-client >= 3.0.20.Final

**Comment by sonots-zozo** [comment]
Seeing release notes of resteasy-client 3.0.20.Final https://issues.jboss.org/secure/ReleaseNote.jspa?version=12333469&styleName=Html&projectId=12310560&Create=Create&atl_token=AQZJ-FV3A-N91S-UDEU_0b5bd47886ec7585fee14d4fee093573dd622b44_lout,
https://issues.jboss.org/browse/RESTEASY-1499 is the one which is related with gzip.
